.github/workflows/release.yml
build/dockerfiles/Dockerfile
build/dockerfiles/Dockerfile.local

Add workflow file and support both local and ci build

chore(ci): add ci pipeline

---

.github/workflows/ci.yml
Makefile
codecov.yml

Chore
- add codecov CI checks
- add codecov pr comments

chore(*): add codecov checks and pr comments

---

.github/ISSUE_TEMPLATE/bug-report.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement.yaml
.github/PULL_REQUEST_TEMPLATE.md

Chore
Add templates for pull requests and issues.

chore(*): add templates for pull requests and issues

---

codecov.yml

Chore
Modify the threshold of codecov to 2%.

chore(*): modify the threshold of codecov

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go

set EstimateContainerCPUUsageFunc as pluggable
Enhancements

refactor(qosaware): refine estimate resource usage

---

pkg/agent/evictionmanager/manager.go
pkg/agent/evictionmanager/podkiller/killer.go
pkg/agent/evictionmanager/podkiller/killer_test.go
pkg/agent/sysadvisor/plugin/metric-emitter/metric_emitter.go

Enhancements
during evicting process, we miss tags for pod info, add this pr to make up this info

emit metrics for pod killing and add tags for victims

---

cmd/katalyst-agent/main.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/network/dynamicpolicy/policy.go
pkg/util/cgroup/common/cgroup_linux.go
pkg/util/cgroup/common/path.go
pkg/util/cgroup/common/path_test.go
pkg/util/cgroup/manager/manager.go
pkg/util/general/common.go
pkg/util/general/log.go
pkg/util/general/log_test.go
pkg/util/machine/topology.go
pkg/util/machine/util.go
pkg/util/machine/util_test.go

refactor
currently, qrm plugin is a little complicated and lack of abstraction for similar functionalities
this pr is for network plugin

refine coding styles for network plugin

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go

Bug fixes
pass ramp up information to sys advisor

fix(qrm): pass ramp up infomation to sys advisor

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/regulator/regulator.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go
pkg/agent/sysadvisor/types/consts.go
pkg/util/general/common.go

feat(sysadvisor): support multi share regions

---

cmd/katalyst-agent/app/agent.go
cmd/katalyst-agent/app/options/global/base.go
pkg/config/agent/global/base.go
pkg/util/general/file.go
pkg/util/general/file_test.go

Enhancements
mark unhealthy for acquiring file locks

support to mark unhealthy for acquiring file locks

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go

fix(sysadvisor): maximize share pool size when disable reclaim

---

pkg/agent/resourcemanager/fetcher/kubelet/topology/podresourcesserver.go
pkg/agent/resourcemanager/fetcher/kubelet/topology/podresourcesserver_test.go

Bug fixes
pod resources filter support pod parameter

pod resources filter support pod parameter

---

pkg/metaserver/spd/checkpoint/checkpoint.go

fix(spd): fix nil reference

---

pkg/metaserver/agent/pod/pod.go
pkg/metaserver/metaserver.go

fix meta server no start success

---

pkg/metaserver/agent/pod/pod.go
pkg/metaserver/external/manager.go
pkg/metaserver/metaserver.go
pkg/metaserver/metaserver_test.go

add pod fetcher health check

---

pkg/util/machine/topology.go

bug
fix ut for memory plugin in mac

fix memory plugin ut for mac

---

pkg/metaserver/spd/fetcher.go

fix(sysadvisor): return notFound error when spd name not found

---

pkg/metaserver/agent/pod/pod.go
pkg/metaserver/agent/pod/pod_stub.go
pkg/util/native/pods.go
pkg/util/native/pods_test.go

Enhancements
add GetContainerID and GetContainerEnvs to pod util.

add GetContainerID and GetContainerEnvs to pod util

---

cmd/katalyst-agent/app/options/qrm/qrm_base.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
pkg/agent/qrm-plugins/util/util.go
pkg/config/agent/qrm/qrm_base.go

feat(qrm): qrm cpu/mem plugins support identifying debug pod

feat(qrm): qrm cpu/mem plugins support identifying debug pod

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_async_handler.go

fix(qrm): fix checkMemorySet skpping judgement

fix(qrm): fix checkMemorySet skpping judgement

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go

fix(sysadvisor): set estimated resource as pod request when ramping up

---

pkg/agent/sysadvisor/test/metacache_test.go
pkg/util/general/log.go
pkg/util/general/log_test.go

Enhancements
support to use logger with pre-defined prefix

support to use logger with pre-defined prefix

---

pkg/agent/evictionmanager/eviction_resp_collector.go

Enhancements
add pod name tag to dry-run metric

chore(eviction): dry-run metric add pod name tag

---

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
pkg/agent/sysadvisor/metacache/metacache.go
pkg/agent/sysadvisor/plugin/metacache/metacache.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_load.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu/helper.go
pkg/agent/sysadvisor/types/helper.go
pkg/agent/sysadvisor/types/types.go
pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
pkg/consts/metric.go
pkg/metaserver/agent/metric/metric.go
pkg/util/general/common.go

features
support isolation based on container load in sysadvisor

Support isolation pools

---

cmd/katalyst-agent/app/options/dynamic/dynamic_base.go

Bug fixes
fix the issue that memory eviction flags will be ignored.
memory eviction flags will be ignored.

fix(eviciton): apply eviction configuration

---

docs/tutorial/colocation.md

typo: nod->node

---

pkg/metaserver/agent/metric/malachite/cgroup/types.go
pkg/metaserver/agent/metric/metric.go

Bug fix
Calculate container cpi metric by delta(cycles)/delta(instructions).

calculate container cpi by cycles and instructions

---

pkg/agent/qrm-plugins/network/staticpolicy/policy.go
pkg/agent/qrm-plugins/network/staticpolicy/policy_test.go
pkg/agent/qrm-plugins/network/staticpolicy/util.go

feat(qrm): network plugin deal with sidecars

feat(qrm): network plugin deal with sidecars

---

pkg/util/eviction/eviction.go
pkg/util/qos/mem_enhancement.go

Refactor
refactor some util function to make it easier to reuse

refactor(util): refine some function related to memory enhancement

---

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/memory_advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server_test.go
pkg/agent/sysadvisor/types/cpu.go
pkg/agent/sysadvisor/types/memory.go

If qrm plugin now listwatch resource server, updating process will be blocked.
Bug fixes

fix(sysadvisor): make resource updating not blocked by resource server

---

pkg/consts/metric.go
pkg/metaserver/agent/agent.go
pkg/metaserver/agent/metric/fake_metric.go
pkg/metaserver/agent/metric/metric.go
pkg/metaserver/agent/metric/metric_test.go
pkg/metaserver/metaserver_test.go
pkg/util/metric/store.go

feat(metaserver): support collecting metrics for qos level

---

pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/const.go

feat(qrm): define memory advisor control knob constants

feat(qrm): define memory advisor control knob constants

---

.github/workflows/ci.yml
codecov.yml

Chore
Always upload coverage file even if the number of changed lines is smaller than 10.

chore(ci): always upload coverage file

---

.github/workflows/ci.yml
codecov.yml

Ignore codecov check if the number of changed lines is smaller than 10.

chore(ci): ignore codecov check if the number of changed lines is smaller than 10

---

docs/install-enhanced-k8s.md

fix broken links in installation guide
#148

chore(doc): fix link in installation guide

---

cmd/katalyst-agent/app/agent.go
cmd/katalyst-agent/main.go

Refactor
refactor the entrance function signature to make it easy to wrap.

refactor(agent): change entrance function signature

---

pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/generic.go

Bug fixes
remove unused sliding window in GenericHeadroomManager

remove unused sliding window in GenericHeadroomManager

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_dedicated.go
pkg/agent/sysadvisor/types/helper.go

fix(assemble): fix using fake NUMA ID to find non binding numas

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_test.go

Enhancements
only enabled advised threshold when reclaim is enabled.

enhancement(eviction): enabled advised threshold when reclaim enabled

---

pkg/metaserver/config/checkpoint.go

Bug fixes
fix unit test race in config manager

fix unit test race in config manager

---

pkg/agent/sysadvisor/types/helper.go

Bug fixes
fix omit zero static pool

fix omit zero static pool

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/validator/validator_cpu_advisor.go

fix(qrm): fix log msg in validateStaticPools

fix(qrm): fix log msg in validateStaticPools

---

pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/advisor.go
pkg/agent/sysadvisor/types/cpu.go

enhancements
add metric for custom metric (about regions)

add kcmas metric for region info

---

.github/workflows/ci.yml

feat(misc): use self hosted runner for ci

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
pkg/agent/qrm-plugins/util/consts.go
pkg/util/timemonitor/time_monitor.go
pkg/util/timemonitor/time_monitor_test.go

feat(qrm): implement time monitor to monitor advisor lw recv status

feat(qrm): implement time monitor to monitor advisor lw recv status

---

pkg/agent/qrm-plugins/network/staticpolicy/policy.go

fix(qrm): fix network plugin possible memory leak

fix(qrm): fix network plugin possible memory leak

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go

Enhancements
Add more advisor metrics

feat(sysadvisor): add more advisor metrics

---

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go

feat(sysadvisor): add metrics for memory advisor

---

pkg/agent/qrm-plugins/advisorsvc/advisor_svc_stub.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go

fix(qrm): add rm/add container with advisor for memory plugin

fix(qrm): add rm/add container with advisor for memory plugin

---

pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go

Enhancements
add memory usage metric

add memory usage metric

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
pkg/agent/qrm-plugins/util/consts.go

feat(qrm): add advisor metrics for memory plugin

feat(qrm): add advisor metrics for memory plugin

---

pkg/agent/qrm-plugins/network/state/util.go
pkg/agent/qrm-plugins/network/staticpolicy/policy.go
pkg/agent/qrm-plugins/network/staticpolicy/policy_test.go
pkg/agent/qrm-plugins/network/staticpolicy/util.go

Bug fixes
return an error if no available nics on a node
panic if no available nics on a node

fix(qrm): return an error if no available nics on a node

---

cmd/katalyst-controller/app/options/spd.go
pkg/config/controller/spd.go
pkg/controller/spd/spd.go
pkg/controller/spd/spd_test.go

feat(spd): make spd indicator plugins configurable

---

cmd/katalyst-agent/app/agent/qrm/memory_plugin.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go

Features
With this PR, we can register some more memory plugins based on periodicalhandler manager
None
None.

adding support to periodicalhandler manager in memory plugin

---

pkg/consts/metric.go
pkg/metaserver/agent/metric/malachite/fetcher.go

bug fixes
unify malachite metrics to a standard

refine malachite metrics to unified units

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go

feat(qrm): judge shoudSharedCoresRampUp to avoid vibrating in takeover procedure

feat(qrm): judge shoudSharedCoresRampUp to avoid vibrating in takeover procedure

---

pkg/custom-metric/collector/prometheus/collector_promethes.go
pkg/custom-metric/collector/prometheus/collector_test.go
pkg/custom-metric/collector/prometheus/scrape.go
pkg/util/native/container.go
pkg/util/native/pods.go
pkg/util/native/pods_test.go
pkg/util/service-discovery/discovery.go

enhancements
refine kcmas to support multiple host ips for ipv4/ipv6 stacks

refine kcmas to support multiple host ips

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go

fix(qrm): still try to ramp up if specified pool entry doesn't exist

fix(qrm): still try to ramp up if specified pool entry doesn't exist

---

pkg/controller/lifecycle/agent-healthz/healthz_controller.go
pkg/controller/lifecycle/agent-healthz/healthz_controller_test.go
pkg/controller/lifecycle/cnc_test.go

Bug fixes
fix lifecycle check pod ready failed

fix lifecycle agent pod ready check

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_test.go

Bug fixes
fix bugs for isolation regions

fix bugs for justifying isolation region names

---

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go

bug fixes
fix bugs for isolation owner pool setting and support multiple containers to share region

fix bugs for isolation ownerpool setting and support multiple containers to share region

---

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go

fix(qrm): mem plugin pushes containers to mem adviosr at starting

fix(qrm): mem plugin pushes containers to mem adviosr at starting

---

pkg/agent/qrm-plugins/network/staticpolicy/policy.go
pkg/util/machine/network_linux.go
pkg/util/machine/network_linux_test.go

Bug fixes
fix the bug caused by invalid numanode value on VMs
it also fixes the problem if device/enable does not exist on VMs

fix: fix the bug caused by invalid numanode value on VMs

---

pkg/agent/qrm-plugins/network/state/util.go

bug fixes
fix invalid network reservation for network plugin

fix invalid network reservation for network plugin

---

docs/install-enhanced-k8s.md

chore(doc): update enhanced k8s installation guide for head

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/agent/sysadvisor/types/cpu.go

Bug fixes/Enhancements
Fix and complement region tags

fix and complement region tags

---

pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go

refactor(sysadvisor): refine log format

---

pkg/custom-metric/store/local/local_store.go

Bug fixes
fix kcmas use label selector failed for mistake usage of meta informer

fix kcmas use label selector failed

---

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
pkg/custom-metric/provider/provider.go
pkg/custom-metric/store/data/aggregator.go
pkg/custom-metric/store/data/cache.go
pkg/custom-metric/store/data/const.go
pkg/custom-metric/store/local/local_store.go
pkg/custom-metric/store/local/server.go
pkg/custom-metric/store/remote/remote_store.go

bug fixes
add more metrics for kcmas and refine performance for it

add more metrics for kcmas and refine performance for read requests

---

pkg/controller/kcc/cnc.go
pkg/controller/kcc/cnc_test.go
pkg/controller/lifecycle/cnc.go
pkg/controller/lifecycle/cnc_test.go
pkg/controller/lifecycle/cnr.go
pkg/controller/lifecycle/cnr_test.go

fix cnc update

---

pkg/util/general/window.go
pkg/util/general/window_test.go

fix(util): return nil when samples pool is not filled

---

pkg/custom-metric/store/remote/remote_store.go
pkg/custom-metric/store/remote/sharding.go

bug fixes
fix memory leak by closing cancelled http requests

fix memory leak by close all response body

---

pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go

Bug fixes
report cnr topology filter out failed and succeeded pod.

getZoneAllocations filter out failed and succeeded pod

---

cmd/katalyst-agent/app/agent/qrm/io_plugin.go
cmd/katalyst-agent/app/enableagents.go
cmd/katalyst-agent/app/options/qrm/io_plugin.go
cmd/katalyst-agent/app/options/qrm/qrm_base.go
pkg/agent/qrm-plugins/io/io.go
pkg/agent/qrm-plugins/io/staticpolicy/policy.go
pkg/agent/qrm-plugins/io/staticpolicy/policy_test.go
pkg/config/agent/qrm/io_plugin.go
pkg/config/agent/qrm/qrm_base.go
pkg/util/cgroup/common/types.go
pkg/util/cgroup/manager/cgroup.go
pkg/util/cgroup/manager/manager.go
pkg/util/cgroup/manager/v1/fs_linux.go
pkg/util/cgroup/manager/v1/fs_unsupported.go
pkg/util/cgroup/manager/v2/fs_linux.go
pkg/util/cgroup/manager/v2/fs_linux_test.go
pkg/util/cgroup/manager/v2/fs_unsupported.go

implement io qrm plugin to support io control operations

implement io qrm plugin

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go

fix(sysadvisor): fix invalid cpulimit

---

pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go

bug fixes
fix bugs for owner pool name with isolation

fix owner pool name for isolated container

---

cmd/katalyst-agent/app/options/qrm/qrm_base.go
pkg/agent/qrm-plugins/cpu/consts/consts.go
pkg/agent/qrm-plugins/cpu/cpu.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/util.go
pkg/agent/qrm-plugins/cpu/nativepolicy/policy.go
pkg/agent/qrm-plugins/cpu/nativepolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/cpu/nativepolicy/policy_hint_handlers.go
pkg/agent/qrm-plugins/cpu/nativepolicy/policy_test.go
pkg/agent/qrm-plugins/cpu/nativepolicy/util/util.go
pkg/agent/qrm-plugins/cpu/util/util.go
pkg/agent/qrm-plugins/cpu/util/util_test.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/util.go
pkg/agent/qrm-plugins/util/util.go
pkg/config/agent/qrm/qrm_base.go

feat(qrm): support option which prefers to use kubelet reserved resource configuration to katalyst reserved resource configuration

feat(qrm): support option which prefers to use kubelet reserved resource configuration to katalyst reserved resource configuration

---

cmd/katalyst-agent/app/options/reporter/reporter_base.go
pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go
pkg/config/agent/reporter/reporter_base.go
pkg/controller/lifecycle/cnr.go

Bug fixes
cherry pick from 8fda89b6c70e7db732e39ea068f73aa675b2f896 to relaese-0.3
Related issues：https://github.com/kubewharf/katalyst-core/pull/250

fix(agent): fix cnr residue when node deletion

---

pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go

bug fixes
fix bugs for advisor

always set isolated container name as region name

---

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_load.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_test.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/types/types.go
pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
pkg/util/general/common.go

styles
add some comments for assemble container-entry and types

refine isolation threshold judgement logic

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go

fix(qrm): clean pool concerning owner pool name instead of specified pool

fix(qrm): clean pool concerning owner pool name instead of specified pool

---

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go

refactor: refine memory log format

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/types/helper.go

fix(sysadvisor): consider pod reclaim disabled

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go

add metrics for failed events

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/types/helper.go

fix(sysadvisor): check pod number for dedicated region

---

pkg/agent/sysadvisor/types/helper.go

Bug fixes
fix region info clone no clone region status

fix region info clone no clone region status

---

pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/advisor.go
pkg/agent/sysadvisor/types/helper.go

Bug fixes
fix node_advisor_knob_status tag

fix node_advisor_knob_status tag

---

pkg/custom-metric/collector/prometheus/scrape.go
pkg/custom-metric/provider/provider_test.go
pkg/custom-metric/provider/util.go
pkg/custom-metric/store/data/cache.go
pkg/custom-metric/store/data/const.go

Bug fixes
fix kcmas precision when some metric with small value

fix kcmas precise when some metric with small value

---

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memset_binder.go

feat(sysadvisor): bind memset to no pressure NUMAs

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go

feat(sysadvisor): add metrics for headroom

---

pkg/agent/sysadvisor/plugin/metacache/metacache.go
pkg/agent/sysadvisor/types/helper.go

Updating cpu_request of containerInfo in periodicWork of MetaCachePlugin

---

.gitignore

ignore test coverage profile file, generated by "make test"

chore: ignore test coverage profile files

---

cmd/katalyst-agent/app/agent.go

styles
move locking file metrics name to const and renaming

move locking file metrics name to const and renaming

---

pkg/util/process/http.go

fix: character type

---

cmd/katalyst-controller/app/options/controllerbase.go
cmd/katalyst-controller/app/options/controllerbase_test.go
pkg/config/controller/spd.go
pkg/controller/lifecycle/cnc_test.go
pkg/controller/spd/spd.go
pkg/util/general.go
pkg/util/spd.go

enhancements
support to select service-profiling workload by selector

wip: support to select service-profiling workload by selector

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_numa_exclusive.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_numa_exclusive_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go

Prevents NAN from being generated due to a division by zero error
#300

enhancement(sysadvisor): Prevents NAN from being generated due to a division by zero error

---

pkg/agent/evictionmanager/podkiller/killer.go
pkg/agent/evictionmanager/podkiller/killer_test.go

Bug fixes
parse container id when stop container

fix(eviction): parse container id when stop container

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton.go

fix(eviction): panic when get evict pods

---

examples/reclaimed-deployment.yaml
examples/reclaimed-large-pod.yaml
examples/reclaimed-normal-pod.yaml

In example/reclaimed-*.yaml
```
katalyst.kubewharf.io/reclaimed_millicpu => resource.katalyst.kubewharf.io/reclaimed_millicpu
katalyst.kubewharf.io/reclaimed_memory => resource.katalyst.kubewharf.io/reclaimed_memory
```

fix: update the ResourceName of reclaim pod in the example directory

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/util/metric/store_util.go

features
support to disable isolations for sysadvisor

support to disable isolation when exceeding total capacities

---

pkg/custom-metric/store/data/internal/internal.go

fix(kcmas): deadlock

---

pkg/agent/evictionmanager/eviction_resp_collector.go

enhancements
add detailed messages for observed/threshold values for eviction

add more eviction messages about threshold and observed values

---

pkg/custom-metric/store/data/cache.go

fix(kcmas): nil pointer

---

pkg/custom-metric/store/data/cache.go

Enhancement
remove some high frequency monitor logic

perf(kcmas): remove high frequency monitor

---

pkg/custom-metric/provider/provider_test.go
pkg/custom-metric/store/data/cache.go
pkg/custom-metric/store/local/local_store.go

enhancement
don't purge useless metric meta for performance

perf(kcmas): don't purge useless metric meta

---

README.md

misc: fix meeting link

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go

feat(qrm): support register handler after group started

feat(qrm): support register handler after group started

---

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go
pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
pkg/util/asyncworker/types.go

refine
refine some comments and coding styles

refine some comments and coding styles

---

pkg/controller/spd/indicator-plugin/manager.go
pkg/controller/spd/spd_indicator.go
pkg/controller/spd/spd_test.go

fix(spd): remove interface

---

pkg/client/control/node.go
pkg/client/control/node_test.go

node updater support patch node status

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_dedicated.go
pkg/agent/sysadvisor/types/cpu.go

fix(sysadvisor): always set regionInfo

---

cmd/katalyst-metric/app/options/store.go
pkg/config/metric/store.go
pkg/custom-metric/provider/provider_test.go
pkg/custom-metric/store/data/cache.go
pkg/custom-metric/store/data/cache_test.go
pkg/custom-metric/store/local/local_store.go

Features
support multiple indexes for kcmas

feat(kcmas): multiple index keys

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/util.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/util_test.go
pkg/config/generic/qos.go
pkg/util/qos/helper/enhancement_helper.go

feat(qrm): refine enhancement & qosLevel updater

feat(qrm): refine enhancement & qosLevel updater

---

cmd/katalyst-agent/app/options/qrm/cpu_plugin.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_test.go
pkg/config/agent/qrm/cpu_plugin.go

enhancement
load pressure eviction plugin support set skip pools by configuraiton

enhancement(eviction): set skip pools via conf

---

cmd/katalyst-agent/app/options/sysadvisor/qosaware/model/borwein/borwein.go
pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
pkg/consts/metric.go

Just try to remove a duplicated logging.

Removing duplicated logging

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
pkg/util/native/pods.go
pkg/util/native/pods_test.go

fix(qrm): use phase pending instead of active to judge if need to ramp up

fix(qrm): use phase pending instead of active to judge if need to ramp up

---

pkg/controller/spd/indicator-plugin/manager.go

fix(spd): fix deadlock

---

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein_test.go
pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go

feat(advisor): enable borwein result fetcher independently

feat(advisor): enable borwein result fetcher independently

---

pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go

feat(advisor): add some metrics for borwein model result fetcher

feat(advisor): add some metrics for borwein model result fetcher

---

pkg/agent/resourcemanager/fetcher/system/systemplugin.go

(cherry picked from commit 0c8f537800893ce105930e716452d6bd8d6bac47)
Enhancements
support report numa count property to kcnr

support report numa count to kcnr

---

CODEOWNERS

enhancements
add owner files to init reviewers for pull requests

Add owners for katalyst

---

cmd/katalyst-agent/app/enableagents.go
pkg/agent/evictionmanager/manager.go
pkg/agent/evictionmanager/plugin/resource/reclaimed_resources.go
pkg/agent/evictionmanager/plugin/resource/reclaimed_resources_test.go
pkg/agent/evictionmanager/plugin/resource/resources.go

refine coding styles for katalyst-agent cmd and eviction plugins

---

pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go

Adding a metric point.
For describing how many containers are detected as overload in a node.

report ratio of overload container

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_none.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_numa_exclusive_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_none.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go

enhancements
add none policy for headroom and provision

add none policy for headroom and provision

---

docs/install-enhanced-k8s.md

misc(doc): update enhanced k8s version for v0.4.0

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go

fix reclaim pool entry of non binding numas in calculation result

---

pkg/metaserver/agent/metric/provisioner/kubelet/client/client.go

bugfix: request summary from podsEndpoint when enable kubelet secure port

---

pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go

The unit of numa_stat is "page" in cgroup1 and "byte" in cgroup2.
Bug fixes

fix(metric): numa memory stats

---

pkg/agent/evictionmanager/manager.go

Bug fixes
fix eviction manager grpc connection leak

fix eviction manager grpc connection leak

---

pkg/config/generic/qos.go

fix qos enhancement

---

cmd/katalyst-agent/app/options/qrm/io_plugin.go
pkg/agent/qrm-plugins/io/handlers/dirtymem/const.go
pkg/agent/qrm-plugins/io/handlers/dirtymem/dirtymem_linux.go
pkg/agent/qrm-plugins/io/handlers/dirtymem/dirtymem_linux_test.go
pkg/agent/qrm-plugins/io/handlers/dirtymem/wbt_linux.go
pkg/agent/qrm-plugins/io/staticpolicy/policy.go
pkg/consts/common.go
pkg/consts/metric.go
pkg/metaserver/agent/metric/helper/consts.go
pkg/metaserver/agent/metric/helper/device.go
pkg/metaserver/agent/metric/helper/device_test.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
pkg/metaserver/agent/metric/provisioner/malachite/types/system.go

Features
WBT switch function is the basis of IO QoS.
For example, when we want to enable IO QoS for a disk,
we need to disable any other throttlings of the corresponding disk, such as writeback throttling.
None.
None.

feat: adding wbt switch function

---

pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server_test.go

Bug fixes
Fix sysadvisor ListWatch stream leak

feat(sysadvisor): fix sysadvisor lw stream leak

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/provisioner/policy/policy_canonical.go

refactor(sysadvisor): add metric and tag

---

pkg/agent/qrm-plugins/io/handlers/dirtymem/dirtymem_unsupported.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/provisioner/memory_provisioner.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/provisioner/policy/policy_canonical.go

refactor(sysadvisor): refine boundType updating logic

---

pkg/agent/evictionmanager/plugin/rootfs/rootfs_pressure.go
pkg/agent/evictionmanager/plugin/rootfs/rootfs_pressure_test.go

fix(eviction): fix rootfs eviction protection

---

pkg/agent/evictionmanager/eviction_resp_collector.go
pkg/agent/evictionmanager/manager.go
pkg/agent/evictionmanager/plugin/rootfs/rootfs_pressure.go

Features
Optimize the logs and metrics of rootfs eviction plugin.

feat(eviction): optimize rootfs eviction logs and metrics

---

cmd/katalyst-agent/app/agent.go

Enhancements
This PR emits a metric when agent starts.

chore(agent): monitor agent start

---

CODEOWNERS

docs
refine owners for sysadvisor

refine code owners for sysadvisor

---

cmd/katalyst-agent/app/options/metaserver/metaserver.go
pkg/agent/orm/endpoint/endpoint.go
pkg/config/agent/metaserver/agent.go
pkg/metaserver/agent/metric/fake_metric.go
pkg/metaserver/agent/metric/metric_impl.go
pkg/metaserver/agent/metric/metric_provisoner.go
pkg/metaserver/agent/metric/provisioner/cgroup/provisioner.go
pkg/metaserver/agent/metric/provisioner/kubelet/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
pkg/metaserver/agent/metric/types/metric.go

enhancements
add new metric-fetcher implementation for cgroup raw metrics

add cgroup metric fetcher in metaserver

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go

Bug fixes
Support creating new pools.

support creating new pools

---

pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go

chore(*): add logs

---

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_balancer.go

Features
when there is a numa hotspot, numa balancer evicts reclaimed pod and balance the memory at the same time.

feat(qrm): do evict and balance at the same time

---

cmd/katalyst-agent/app/agent/context.go

bug fixes
customized plugin manager to skipping running if no handles and registered to avoid logging error logs too frequently

customized plugin manager to skipping running if no handles and registered

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/network/staticpolicy/policy.go

refine(qrm): add metrics for plugin start failed

refine(qrm): add metrics for plugin start failed

---

pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go

Enhancements
cnr reporter add update cnr cost metrics and log

add cnr reporter update cnr cost metrics and log

---

cmd/katalyst-agent/app/options/global/base.go
pkg/config/agent/global/base.go
pkg/util/cnr.go
pkg/util/cnr_test.go
pkg/util/machine/machine_linux.go
pkg/util/machine/topology.go
pkg/util/machine/topology_linux.go

cnr reporter support merge siblings and machine info provide sibling numa info

---

pkg/controller/lifecycle/agent-healthz/healthz_controller.go
pkg/controller/spd/spd.go
pkg/util/native/informer_test.go
pkg/util/native/informer_transformed_pod.go

refine
renaming transformed logic for pod informer

renaming transformed logic for pod informer

---

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_balancer.go

Bug fixes
fix get wrong max latency numa.

fix(sysadvisor): get wrong max latency numa

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go

Enhancements
Optimize advisor qosaware update logic.

feat(sysadvisor): optimize advisor qosaware update logic

---

pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go
pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go

fix invalid type transformation for BorweinInferenceResults

---

pkg/consts/metric.go
pkg/custom-metric/store/remote/remote_store.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
pkg/util/metric/store.go

Enhancements
1. fix bugs for kcmas collecting hang (if corresponding servers are all shut down)
2. add network-related metrics in malachite provisioner

Malachite adapt to network metrics

---

pkg/agent/resourcemanager/fetcher/manager.go
pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go

chore(*): add metrics and logs

---

pkg/agent/sysadvisor/metacache/metacache.go
pkg/agent/sysadvisor/metacache/metacache_test.go
pkg/agent/sysadvisor/plugin/qosaware/server/base_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go

Bug fixes
Fix the concurrent read-write issue in metacache.

feat(sysadvisor): fix the concurrent read-write issue in metacache

---

pkg/agent/resourcemanager/fetcher/manager.go

chore(*): add metric

---

pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go

Bug fixes
only check share and reclaimed cores pod.

feat(advisor): fix cpu advisor calc checking logic

---

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go

skip memory estimation for reclaimed cores pod

---

pkg/metaserver/spd/cache.go
pkg/metaserver/spd/fetcher.go

reduce the frequency of spd manager try to get unused spd from remote api-server

---

.github/workflows/ci.yml

chore
ignore error if coverage uploading failed

ignore error if coverage uploading failed

---

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go
pkg/metaserver/agent/metric/fake_metric.go
pkg/metaserver/agent/metric/metric_impl.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/types/metric.go
pkg/util/metric/store.go

Reverts kubewharf/katalyst-core#499

Revert "refactor(sysadvisor): refine memory guard"

---

pkg/agent/sysadvisor/metacache/metacache.go
pkg/agent/sysadvisor/metacache/metacache_test.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go

Bug fixes
Fix metacache concurrent read/write and add test case for it.

fix(sysadvisor): fix metacache concurrent read/write

---

pkg/agent/qrm-plugins/io/handlers/iocost/iocost_unsupported.go
pkg/agent/qrm-plugins/io/handlers/ioweight/ioweight_unsupported.go

io: adding fake functions for other platforms

---

pkg/agent/sysadvisor/plugin/inference/inference.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/reporter_interface.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_balancer.go

Enhancements
disable some health check rules.

chore(sysadvisor): disable some healthcheck rule

---

pkg/agent/resourcemanager/fetcher/manager.go
pkg/agent/resourcemanager/fetcher/manager_test.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/headroom_reporter.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
pkg/metaserver/metaserver_test.go

Enhancements
refine some healthcheck rule

chore(sysadvisor): refine some healthcheck rule

---

.github/workflows/ci.yml

bug fixes
add codecov uploading secret tokens

add codecov uploading secret tokens

---

.github/workflows/ci.yml
cmd/katalyst-agent/app/options/reporter/kubelet_plugin.go
pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go
pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go
pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go
pkg/config/agent/reporter/kubelet_plugin.go

Cherry-pick
cherry pick of #541: feat(reporter): validate specific resources in pod resources response

cherry pick of #541: feat(reporter): validate specific resources in pod resources response

---

pkg/util/cnr.go

fix MergeAttributes sort zone attribute

---

pkg/agent/sysadvisor/metacache/metacache.go
pkg/controller/overcommit/node/matcher/matcher.go
pkg/controller/vpa/recommend.go
pkg/custom-metric/store/remote/remote_store.go

/kind cleanup
- cleanup deprecated func 
- cleanup useless comment

cleanup deprecated func and useless comment

---

cmd/katalyst-agent/app/options/qrm/io_plugin.go
pkg/agent/qrm-plugins/io/handlers/dirtymem/wbt_linux.go
pkg/config/agent/qrm/io_plugin.go

Enhancements
adding wbt switch function for nvme devices
This patch can help us to fix several io issues, such as dirty throttling, task hung.
None.

feat: adding wbt switch function for nvme devices

---

pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go
pkg/util/machine/topology.go
pkg/util/machine/topology_linux.go
pkg/util/machine/topology_test.go

fix sibling numa set

---

.github/workflows/ci.yml

enhancements
use token when uploading codecov results

use token when uploading codecov results

---

cmd/base/context.go
cmd/base/healthz.go

This PR adds metrics related to healthz.

add healthz metrics

---

pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go

kubelet plugin run add fatal error

---

cmd/katalyst-agent/app/options/sysadvisor/sysadvisor_base.go

Features
Update the default enabled plugins in sysadvisor.

feat(sysadvisor): update default enabled plugins

---

cmd/katalyst-agent/app/options/metaserver/metaserver.go
cmd/katalyst-agent/app/options/metaserver/metric.go
pkg/config/agent/metaserver/agent.go
pkg/metaserver/agent/metric/metric_impl.go
pkg/metaserver/agent/metric/metric_test.go
pkg/metaserver/agent/metric/provisioner/rodan/provisioner.go
pkg/metaserver/agent/metric/types/metric.go

enhancements
refine metric-fetcher to support specified collecting intervals

refine metric-fetcher to support specified collecting intervals

---

pkg/agent/qrm-plugins/cpu/nativepolicy/policy.go
pkg/agent/qrm-plugins/cpu/util/util.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/util.go
pkg/agent/qrm-plugins/util/util.go
pkg/agent/sysadvisor/plugin/overcommitmentaware/realtime/realtime.go
pkg/agent/sysadvisor/plugin/overcommitmentaware/reporter/reporter.go
pkg/util/kubelet/config/kubeletconfig.go
pkg/util/kubelet/config/kubeletconfig_test.go

Features
move all dependencies for kubelet configuration to util

feat(*): move all dependency for kubelet configurations to util

---

cmd/katalyst-agent/app/options/global/base.go
pkg/config/agent/global/base.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go

fix: ignore not existed cgroup paths

---

pkg/controller/vpa/util/resource.go
pkg/controller/vpa/util/resource_test.go
pkg/controller/vpa/vpa.go
pkg/controller/vpa/vpa_status.go
pkg/util/native/resources.go

refine vpa apply strategy

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go

Enhancements
support ignore the share cores pod without request

feat(advisor): skip the share pool without cpu request

---

pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go
pkg/agent/resourcemanager/fetcher/plugin/endpoint.go
pkg/agent/sysadvisor/plugin/overcommitmentaware/reporter/reporter.go

remote reporter plugin and topology adapter support context timeout

---

pkg/agent/qrm-plugins/cpu/util/util.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/util.go
pkg/util/kubelet/config/kubeletconfig.go

refine(util): refine getting reserved

refine(util): refine getting reserved

---

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
pkg/util/asyncworker/async_limited_workers.go
pkg/util/asyncworker/async_workers_test.go
pkg/util/asyncworker/types.go

refactor(async): support limited async workers

---

cmd/katalyst-agent/app/agent/audit.go
cmd/katalyst-agent/app/enableagents.go
cmd/katalyst-agent/app/options/global/audit.go
cmd/katalyst-agent/app/options/options.go
pkg/agent/audit/manager.go
pkg/agent/audit/manager_test.go
pkg/agent/audit/sink/basesink.go
pkg/agent/audit/sink/logbased.go
pkg/agent/audit/sink/types.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go
pkg/config/agent/agent_base.go
pkg/config/agent/global/audit.go
pkg/consts/common.go
pkg/util/cgroup/common/cgroup_linux.go
pkg/util/cgroup/common/types.go
pkg/util/cgroup/manager/cgroup.go
pkg/util/cgroup/manager/v1/fs_linux.go
pkg/util/cgroup/manager/v2/fs_linux.go
pkg/util/eventbus/event_bus.go
pkg/util/eventbus/event_bus_test.go
pkg/util/eventbus/types.go

This PR adds a framework to gather all the control actions(like applying cgroups, system calls and etc)executed by katalyst then send them to a data warehouse. This mechanism aims to provide audit data for users. If there is a need to integrate a 3rd-party storage, we can simply implement a `Sink` interface to send data to it.

feat(general): audit manager framework

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/cpu/util/util.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
pkg/agent/qrm-plugins/util/consts.go
pkg/util/timemonitor/time_monitor.go
pkg/util/timemonitor/time_monitor_test.go

feat(qrm): 1. refine timemonitor until 2. fallback when cpu advisor is unhealthy

feat(qrm): 1. refine timemonitor until 2. fallback when cpu advisor is unhealthy

---

pkg/util/asyncworker/async_limited_workers.go

fix(util): fix deadlock

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpuadvisor/helper.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_metric.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/validator/validator_cpu_advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/cache_reaper.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go

fix(qrm): always allocate reclaim pool lastly

fix(qrm): always allocate reclaim pool lastly

---

pkg/controller/lifecycle/agent-healthz/helper/healthz_check.go

enhancement
add cluster health metrics

feat(lifecycle): emitter cluster health rate

---

cmd/katalyst-agent/app/agent/audit.go
pkg/util/eventbus/event_bus.go
pkg/util/eventbus/event_bus_test.go

Enhancements
This PR adds some metrics about eventbus.

feat(audit): eventbus metrics

---

pkg/agent/sysadvisor/plugin/qosaware/server/base_server.go

Enhancements
Add log for API RemovePod and AddContainer in qosaware server.

feat(advisor): add debug log for qosaware server

---

pkg/controller/spd/spd_indicator.go

Compatible with spd with empty scope

---

pkg/agent/sysadvisor/plugin/qosaware/qos_aware_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/server/base_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server_test.go
pkg/agent/sysadvisor/plugin/qosaware/server/server.go
pkg/agent/sysadvisor/plugin/qosaware/server/server_test.go

Enhancements
Optimize the advisor run servers logic

feat(sysadvisor): optimize run servers

---

pkg/agent/sysadvisor/plugin/qosaware/server/server.go

Bug fixes
Make sure server running before stop

fix(advisor): fix server start wait

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go

refine(qrm): remove pod return immediately when pod already removed

refine(qrm): remove pod return immediately when pod already removed

---

cmd/katalyst-agent/app/options/dynamic/adminqos/advisor/cpu_provision.go

fix: add flags

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper_test.go

fix(advisor): fix reclaim overlap share cores

---

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_offloading.go

chore(tmo): add more logs

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server_test.go
pkg/util/general/healthz.go

Enhancements
Support short time health check

fix(advisor): optimize lw health check

---

cmd/katalyst-agent/app/agent/orm.go
cmd/katalyst-agent/app/options/orm/orm_base.go
cmd/katalyst-agent/app/options/reporter/kubelet_plugin.go
pkg/agent/orm/manager.go
pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go
pkg/config/agent/orm/orm_base.go
pkg/config/agent/reporter/kubelet_plugin.go

Bug fixes
1. Add NativeQosClass to ResourceReq in ORM
2. Fix resource plugin registration path of ORM
3. Fix kubelet reporter plugin pod resources filter in native QoS scenario

fix: fix some orm and reporter plugin issues

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go

feat(qrm): refine getting hint by memory bandwidth

feat(qrm): refine getting hint by memory bandwidth

---

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/provision/policy_base.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/regulator/regulator.go
pkg/agent/sysadvisor/types/consts.go
pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_base.go

Enhancements
cpu regulator support config parameter

cpu regulator support config parameter

---

pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go

Enhancements
Reduce move_pages  max granularity from 20MB to 5MB to optimize jitter problems

reduce move_pages granularity

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/util/machine/zone.go
pkg/util/machine/zone_linux.go

Bug fixes
If the region is not reclaimable, we have no need to care about whether
it is upper bound.

fix: check having upper bound

---

pkg/util/cgroup/manager/v1/fs_unsupported.go
pkg/util/cgroup/manager/v2/fs_unsupported.go
pkg/util/machine/zone_unsupported.go

unsupportedManager: adding GetMemoryPressure

---

cmd/katalyst-agent/app/options/qrm/io_plugin.go
pkg/agent/qrm-plugins/io/handlers/dirtymem/dirtymem_linux_test.go
pkg/agent/qrm-plugins/io/handlers/dirtymem/wbt_linux.go
pkg/config/agent/qrm/io_plugin.go
pkg/consts/common.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go

Enhancements: adding support to wbt config for virtio disk
On producation area, there are several issues related to low performance virtio disk.
High io-wait issues realted to virtio disk.
None

dirtymem: adding support to virtio disk

---

pkg/agent/evictionmanager/plugin/memory/numa_pressure_test.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/cache_reaper.go
pkg/consts/metric.go
pkg/metaserver/agent/metric/fake_metric.go
pkg/metaserver/agent/metric/helper/container.go
pkg/metaserver/agent/metric/metric_impl.go
pkg/metaserver/agent/metric/metric_test.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
pkg/metaserver/agent/metric/provisioner/malachite/types/cgroupv1.go
pkg/metaserver/agent/metric/provisioner/malachite/types/cgroupv2.go
pkg/metaserver/agent/metric/provisioner/rodan/provisioner.go
pkg/metaserver/agent/metric/provisioner/rodan/provisioner_test.go
pkg/metaserver/agent/metric/types/metric.go
pkg/util/metric/store.go
pkg/util/metric/store_util.go

feat:  report NUMA cpu usage

---

.github/workflows/ci.yml

Repo infra
Print a summary of unit tests in CI.

ci: add test summary

---

pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter_test.go

Test fix
test code only - not production code
sorting slice in deterministic order to ensure consistent equality check

fix (test): test code fix TestNodeMetricUpdate

---

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go

chore(qrm): support migrate pages in handleAdvisorCPUSetMems

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go

fix(sysadvisor): fix assemble logic of multi share region

---

pkg/metaserver/agent/kubeletconfig/kubeletconfig.go

support get kubelet config via insecure port

feat(*): support get kubelet config via insecure port

---

pkg/agent/evictionmanager/plugin/memory/numa_pressure_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/consts/metric.go
pkg/metaserver/agent/metric/fake_metric.go
pkg/metaserver/agent/metric/metric_impl.go
pkg/metaserver/agent/metric/metric_test.go
pkg/metaserver/agent/metric/provisioner/malachite/client/client_system_test.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/types/system.go
pkg/metaserver/agent/metric/types/metric.go
pkg/util/metric/store.go
pkg/util/metric/store_test.go
pkg/util/spd_indicator.go

support cpu codename aware indicator

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/resource.go
pkg/agent/sysadvisor/plugin/qosaware/resource/resource_stub.go
pkg/agent/sysadvisor/plugin/qosaware/server/base_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server_test.go
pkg/agent/sysadvisor/plugin/qosaware/server/server.go
pkg/agent/sysadvisor/plugin/qosaware/server/server_test.go

Refactor
Change the interface between qrm plugins and sysadvisor from the existing asynchronous bidirectional model to a synchronous unidirectional model.

refactor(sysadvisor): synchronous api between qrm-plugins and sys-advisor

---

pkg/metaserver/agent/kubeletconfig/kubeletconfig.go

Bug fixes
remove extra slashes in the URL when calling the configz endpoint

 fix(qrm): remove extra slashes in the URL when calling the configz endpoint

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go

fix getIndicators use minTarget

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
pkg/util/general/healthz.go
pkg/util/general/healthz_test.go

Bug fix
- fix deadlock on sysadvisor update panic
- fix MetaCache data races
- simplify locking scheme in healthz

fix(advisor): fix deadlock on panic

---

cmd/base/healthz.go

Enhancements
add message tag in healthz metric

add message tag in healthz metric

---

pkg/agent/qrm-plugins/network/staticpolicy/policy.go
pkg/agent/qrm-plugins/network/staticpolicy/util.go

fix(net): not change request hint for network plugin

---

pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go

refactor: relace raw CPI metric with exponential weighted moving average

---

pkg/consts/metric.go
pkg/metaserver/agent/metric/fake_metric.go
pkg/metaserver/agent/metric/metric_impl.go
pkg/metaserver/agent/metric/metric_test.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/types/system.go
pkg/metaserver/agent/metric/types/metric.go

feat(metric): add NIC speed, tx_bps, rx_bps metrics

feat(metric): add NIC speed, tx_bps, rx_bps metrics

---

pkg/agent/sysadvisor/plugin/inference/inference.go
pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/latencyregression/latency_regression.go
pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/latencyregression/latency_regression_test.go
pkg/agent/sysadvisor/plugin/inference/models/borwein/consts/consts.go
pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/model.go
pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod_test.go

Enhancements
Support new borwein model: fetch result from borwein sock and push to emitter

feat(sysadvisor): support borwein latency regression model

---

pkg/util/general/deepcopy.go
pkg/util/general/deepcopy_test.go

chore(util): add DeepCopyIntToStringMap to util

---

pkg/util/machine/network_linux.go

feat(network): support bond nic

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go

Change-Id: Ibe8c5b5bf5826192f1a232521b658ebef6ec1d75

fix(sysadvisor): fix unit test failed of get headroom

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_util.go

Change-Id: Idf52dc0cc3f842351d43bfba82c62376aff4cd54

fix(sysadvisor): skip invalid numa for headroom calculation

---

Makefile
pkg/controller/spd/spd_indicator.go
pkg/controller/spd/spd_test.go
pkg/util/spd.go

fix(spd): fix spd mergeIndicatorSpec

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_checkpoint.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/state/state_checkpoint.go
pkg/controller/spd/cnc_test.go

fix(qrm): qrm cpu/memory plugin state restore include headroom

---

pkg/util/cgroup/manager/cgroup.go
pkg/util/cgroup/manager/v1/fs_linux.go

chore(*): GetPidsWithRelativePath support multi-subsystem

---

pkg/metaserver/kcc/checkpoint.go
pkg/metaserver/kcc/checkpoint_test.go
pkg/util/kcct.go

fix(kcc): fix kcc update kcct status not only with generic status

---

pkg/custom-metric/collector/prometheus/collector_promethes.go

fix(kcmas): fix kcmas checkTargetPod ignore not ready pod

---

pkg/controller/strategygroup/strategygroup_test.go

fix(strategy_group): fix unit-tests race in strate_group controller

fix(strategy_group): fix unit-tests race in strate_group controller

---

cmd/katalyst-agent/app/options/qrm/qrm_base.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go
pkg/config/agent/qrm/qrm_base.go

… as a option
Features
support snb pod preferentially allocated on high numa node

feat(qrm): support snb pod preferentially allocated on high numa node

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go

Bug fixes/Enhancements
typo fix 、sysadvisor and qrm health check optimize

Katalyst healthz check optimize

---

.github/workflows/ci.yml
.github/workflows/status-check.yml

fixes
Update Ubuntu 20.04 LTS runner version to 24.04
https://github.com/actions/runner-images/issues/11101

chore(git-ci): update runner version

---

pkg/agent/evictionmanager/eviction_resp_collector.go

Bug fix
Fix `rule.RuledEvictPod.EvictPod` null pointer issue

fix(evictionmanager): fix EvictPod null pointer issue

---

pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter_test.go

fix(sysadvisor): report zero resource when podList is nil

---

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/resourcemanager/fetcher/manager.go
pkg/util/general/healthz.go
pkg/util/general/healthz_test.go

Bug fixes
unexpected error logs will keep printing.
fix katalyst error log: 
E0412 16:01:09.950247       1 healthz.go:225] [katalyst-core/pkg/util/general.UpdateHealthzState] check rule reporter_push_content not found

fix(reporter): fix reporter pushContent health checker

---

pkg/metaserver/kcc/manager.go
pkg/metaserver/kcc/manager_test.go

Enhancements
Introduce a new ConfigurationHook type and add support for registering hooks in the DynamicConfigManager. These hooks allow triggering custom actions when the dynamic configuration is updated, enhancing the flexibility of the configuration management system.

feat(kcc): add config hooks for dynamic configuration updates

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go
pkg/config/agent/dynamic/adminqos/advisor/cpu_provision.go
pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
pkg/metaserver/agent/agent.go

feat: add cpu_usage_ratio as target indicator of dedicated_cores region

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_metric.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/metric_hint.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/metric_hint_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
pkg/agent/qrm-plugins/util/consts.go
pkg/config/agent/dynamic/dynamic_base.go
pkg/config/agent/dynamic/metricthreshold/metric_threshold.go
pkg/consts/strategy_names.go

feat(qrm): implement metric preferred NUMA allocation

feat(qrm): implement metric preferred NUMA allocation

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_checkpoint.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_test.go
pkg/agent/qrm-plugins/cpu/nativepolicy/policy.go
pkg/agent/qrm-plugins/cpu/nativepolicy/policy_test.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/state/state_checkpoint.go
pkg/agent/qrm-plugins/network/state/state_checkpoint.go
pkg/agent/qrm-plugins/network/staticpolicy/policy.go
pkg/agent/qrm-plugins/network/staticpolicy/policy_test.go

feat(qrm): add qrm store state metrics and fix no memory get hint metrics

---

pkg/config/agent/dynamic/strategygroup/strategy_group.go
pkg/consts/strategy_names.go

feat(strategy_group): add placeholder for initial strategy group

feat(strategy_group): add placeholder for initial strategy group

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_threshold.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_threshold_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/metric_hint.go
pkg/config/agent/dynamic/metricthreshold/metric_threshold.go

Bug fixes
add threshold to metric map in numa cpu pressure eviction plugin

fix(qrm): fix numa cpu eviction threshold key

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
pkg/agent/sysadvisor/metacache/util.go
pkg/agent/sysadvisor/metacache/util_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_dynamic_quota.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_linux_test.go

fix(sysadvisor): quota ctrl knob sanity check

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/metric_hint.go

Bug fixes
filtering insufficient NUMA when allocating NUMAs by metrics

fix(qrm): filtering insufficient NUMA when allocating NUMAs by metrics

---

cmd/katalyst-agent/app/options/dynamic/adminqos/eviction/cpu_pressure_eviction.go
cmd/katalyst-agent/app/options/dynamic/adminqos/eviction/numa_cpu_pressure_eviction.go
cmd/katalyst-agent/app/options/qrm/cpu_plugin.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_numa.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_numa_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_threshold.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
pkg/config/agent/dynamic/adminqos/eviction/cpu_pressure_eviction.go
pkg/config/agent/dynamic/adminqos/eviction/eviction_base.go
pkg/config/agent/dynamic/adminqos/eviction/numa_cpu_pressure_eviction.go
pkg/config/agent/qrm/cpu_plugin.go

numa allocation and numa eviction remove sg

---

cmd/base/options/log.go
pkg/util/general/log.go

chore: support to set klog max size

---

cmd/katalyst-agent/app/options/dynamic/dynamic_base.go
cmd/katalyst-agent/app/options/dynamic/strategygroup/strategy_group.go
cmd/katalyst-agent/app/options/sysadvisor/qosaware/model/borwein/borwein.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_threshold.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_threshold_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/metric_hint.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/metric_hint_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go
pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go
pkg/config/agent/dynamic/dynamic_base.go
pkg/config/agent/dynamic/metricthreshold/metric_threshold.go
pkg/config/agent/dynamic/strategygroup/strategy_group.go
pkg/config/agent/sysadvisor/qosaware/model/borwein/borwein.go
pkg/util/strategygroup/strategy_group.go
pkg/util/strategygroup/strategy_group_test.go

refactor strategy group

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_numa.go
pkg/agent/qrm-plugins/util/util.go
pkg/agent/qrm-plugins/util/util_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_dynamic_quota.go
pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
pkg/util/machine/topology.go

Enhancements
Remove strict validation requiring CPUs to be evenly divisible by NUMA count Update calculation to use ceiling division for more flexible CPU allocation Adjust test case to reflect new behavior

refactor(qrm-plugins): handle uneven CPU distribution across NUMAs

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go
pkg/metaserver/agent/metric/helper/reclaim.go

chore: add cgroupPath for reclaim metrics

---

cmd/katalyst-agent/app/options/sysadvisor/metric-emitter/metric_emitter_plugin.go
pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/node.go
pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/node_test.go
pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
pkg/config/agent/sysadvisor/metric-emitter/metric_emitter_plugin.go
pkg/consts/common.go
pkg/consts/metric.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner_calculate.go
pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
pkg/metaserver/agent/metric/provisioner/malachite/types/cgroupv1.go
pkg/metaserver/agent/metric/provisioner/malachite/types/cgroupv2.go
pkg/metaserver/agent/metric/provisioner/malachite/types/common.go
pkg/metaserver/agent/metric/provisioner/malachite/types/system.go

- expose malachite reported memory bandwidth to kcmas

feat: support malachite resctrl membandwidth report

---

pkg/agent/evictionmanager/conditions.go
pkg/agent/evictionmanager/conditions_test.go
pkg/agent/evictionmanager/manager.go
pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go
pkg/agent/resourcemanager/reporter/cnr/cnrreporter_test.go
pkg/client/control/reporter.go
pkg/client/control/reporter_test.go
pkg/controller/lifecycle/agent-healthz/handler/handler_generic.go
pkg/util/cnr.go
pkg/util/cnr_test.go

Enhancements
- Add new CNR taint reporting functionality to eviction manager
- Implement CNR taint utilities including filtering and diffing
- Introduce generic reporter plugin for CNR taint updates

feat(eviction): add CNR taint reporting support

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler.go

Bug fixes
Add checks to skip emitting metrics when cpuset size or cpu request is zero to avoid division by zero. Also add outOfTolerance flag to metrics to indicate when cpu allocation exceeds request.

fix(cpu/dynamicpolicy): skip zero cpuset or cpu request in metrics

---

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_util.go

fix(sysadvisor): get reclaimed NUMA binding topo

---

pkg/agent/sysadvisor/plugin/qosaware/resource/helper/memory_test.go

Bug fixes
Remove dependency on options package and use direct Configuration constructor

refactor(memory_test): simplify test configuration initialization

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_async_handler.go
pkg/metaserver/agent/pod/pod_stub.go
pkg/util/native/pods.go

Enhancements
check-cpuset healthz check rule optimize

fix(qrm): check-cpuset healthz check rule optimize

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go

fix reject rnb pod with sidecar

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/hintoptimizer/policy/memorybandwidth/optimizer.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/hintoptimizer/policy/memorybandwidth/optimizer_test.go
pkg/agent/qrm-plugins/cpu/util/util.go

Bug fixes
Add ErrNoAvailableMemoryBandwidthHints for memory bandwidth allocation checks

fix(cpu): add memory bandwidth hints error for cpu plugin

---

pkg/agent/sysadvisor/metacache/checkpoint.go
pkg/agent/sysadvisor/metacache/metacache.go
pkg/agent/sysadvisor/plugin/qosaware/qos_aware.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/headroom_reporter.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/headroom_reporter_test.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/manager.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/cpu.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/generic.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/generic_test.go
pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/memory.go
pkg/agent/sysadvisor/types/cpu.go
pkg/agent/sysadvisor/types/helper.go

feat: store headroom to metaCache

---

pkg/agent/evictionmanager/plugin/memory/numa_pressure.go
pkg/config/agent/dynamic/adminqos/eviction/memory_pressure_eviction.go

Enhancements
More scenarios need these enhancements, such as GPU
None
None

numa_eviction: adding critical eviction

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/hintoptimizer/policy/memorybandwidth/optimizer.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/hintoptimizer/policy/memorybandwidth/optimizer_test.go

Enhancements
Move memory bandwidth request validation before NUMA allocation check Clean up parameter alignment in calculateHintMemoryBandwidthAvailability

refactor(memorybandwidth): reorder checks and improve code structure

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/hintoptimizer/policy/canonical/optimizer.go

Features
consider cpu request in dynamic packing

feat(qrm): consider request in dynamic packing

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler.go
pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_async_handler.go

fix(qrm): fix health state

---

cmd/katalyst-agent/app/options/dynamic/adminqos/reclaimedresource/reclaimedresource_base.go
go.mod
go.sum
pkg/agent/qrm-plugins/commonstate/state.go
pkg/agent/qrm-plugins/commonstate/util.go
pkg/agent/qrm-plugins/commonstate/util_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go
pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper.go
pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
pkg/config/agent/dynamic/adminqos/reclaimedresource/reclaimedresource_base.go
pkg/util/qos/cpu_enhancement.go

Features
- Add DisableReclaimSharePools configuration to control reclaim for specific pools
- Refactor share region info extraction to include reclaim enable status
- Improve CPU provision calculation considering reclaim enable status

feat(resource): add disable reclaim for share pools and improve CPU provision logic

---

pkg/metaserver/spd/cache.go
pkg/metaserver/spd/fetcher.go

feat: cache not existed spd

---

pkg/util/native/pods.go

fix(sysadvisor): pending Pods is considered as Active

---

pkg/agent/qrm-plugins/cpu/dynamicpolicy/irqtuner/controller/controller.go

fix(irq-tuning): fix irq-core selection
bugfix
fix a bug of irq core selection

fix(irq-tuning): fix irq-core selection

---

pkg/controller/lifecycle/agent-healthz/helper/healthz_check.go

add metrics agent_deploy_total to indicate the size of the deployed cluster

feat(controller): add metric agent_deployed_node_total
