kubewharf/katalyst-core

go.mod, pkg/config/agent/global/metaserver.go, pkg/metaserver/external/cgroupid/manager.go, pkg/metaserver/external/cgroupid/manager_test.go, pkg/metaserver/external/manager.go, pkg/metaserver/external/manager_test.go, pkg/metaserver/metaserver.go, pkg/util/cgroup/common/types.go, pkg/util/cgroup/manager/cgroup.go, pkg/util/cgroup/manager/cgroup_test.go, pkg/util/cgroup/manager/v2/fs_linux.go, pkg/util/external/network/manager.go, pkg/util/external/network/manager_test.go, pkg/util/external/rdt/manager.go, pkg/util/external/rdt/manager_test.go, pkg/util/general/endian.go
Features
Introduce an external manager framework to:
- Execute configurations beyond the scope of the OCI specification;
- Dynamically manage the mapping between a container and its corresponding cgroup ID, thereby facilitating the implementation of future QoS management solutions based on eBPF.
Fix #4
=> feat(external-manager): add external manager framework

pkg/agent/sysadvisor/metacache/metacache.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
Style
change the elements in sys-advisor policies to small lowercases to avoid unexpected writes
=> refine implementation of sysadvisor policies

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go, pkg/util/cgroup/manager/v2/fs_linux.go
…on socks existing before listening them
fix
ensure directories of qrm sysadvisor communication socks existing before listening them
=> fix(qrm_sysadvisor): ensure directories of qrm sysadvisor communication socks existing before listening them

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
GetBindingNumas and TryUpdateProvision both hold mutex lock.
Bug fixes
=> fix(sysadvisor): fix deadlock

pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
Enhancements
add node name as selectors for pod-level metric in kcmas, to reduce to overhead of client-side matching for pod and node
=> add node name label for pod metric in kcmas

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
binding numas of dedicated_cores is fixed, and binding numas of share_cores is updated when updateNonExclusiveNumas, so we have no need to clear them.
Bug fixes
=> fix(sysadvisor): not clear binding numas any more

pkg/util/general/file.go, pkg/util/general/file_test.go
enhancements
sometimes we need to parse data from a given file, so add a general util function to handle this
=> add util to read file into string slices

pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/generic.go
=> refactor(sysadvisor): emit metrics even when reclaim disabled

pkg/metaserver/agent/agent_test.go, pkg/metaserver/agent/pod/pod.go, pkg/metaserver/agent/pod/pod_stub.go, pkg/metaserver/agent/pod/runtime.go
=> feat(metaserver): support get pod by uid

.github/workflows/status-check.yml
Chore
Add PR status checks to the CI pipeline.
=> chore(*): add pr status check to CI pipeline

pkg/controller/vpa/util/api.go, pkg/controller/vpa/vpa_status.go, pkg/controller/vpa/vparec.go, pkg/controller/vpa/vparec_test.go, pkg/util/vpa.go
Bug fixes
fix vpa condition RecommendationApplied
=> fix vpa condition RecommendationApplied

pkg/util/cgroup/common/cgroup_unsupported.go
=> fix ut failed on macOS

cmd/katalyst-agent/app/options/global/metaserver.go, pkg/config/agent/global/metaserver.go, pkg/metaserver/metaserver.go, pkg/util/cnr_topology.go
Bug fixes
1. add dynamic config disable configuration
2. fix zone allocations out of order
=> add dynamic config disable configuration and fix zone allocations out of order

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/regulator/regulator.go, pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go
=> fix(sysadvisor): fix failed to find regions and pools

pkg/agent/qrm-plugins/cpu/dynamicpolicy/allocation_handlers.go
Bug fixes
fix(qrm): set sidecar owner pool name same to its main container
=> fix(qrm): set sidecar owner pool name same to its main container

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/headroom/policy_base.go, cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/headroom/policy_canonical.go, cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/memory_advisor.go, pkg/agent/resourcemanager/reporter/manager_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_buffer.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_test.go, pkg/config/agent/sysadvisor/qosaware/resource/memory/headroom/policy_base.go, pkg/config/agent/sysadvisor/qosaware/resource/memory/headroom/policy_canonical.go, pkg/config/agent/sysadvisor/qosaware/resource/memory/memory_advisor.go
Features
Current canonical memory headroom policy only consider the memory estimation of non-reclaimed QoS container, and uses the RSS memory to estimate, which may trigger memory reclamation frequently when shared or dedicated QoS container use much more cache and shmem in high load case, so we also need consider them in memory estimation and add extra memory margin.
In the low load case, the machine has enough free memory, the extra memory margin or cache can also oversold to reclaimed QoS worklaod to increase memory utilization.
=> memory headroom canonical policy support enable buffer

cmd/katalyst-agent/app/options/global/metaserver.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/helper.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_test.go, pkg/metaserver/metaserver.go, pkg/metaserver/spd/fetcher.go, pkg/metaserver/spd/fetcher_test.go, pkg/metaserver/spd/manager.go, pkg/util/spd_indicator.go
Features
We need use a service profiling manager implemented in the meta server to manage service level status for each pod. For example, agents can use it to judge whether this pod can be reclaimed according to this service performance.
=> support service profiling manager

cmd/base/options/qos.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/allocation_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/hint_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/allocation_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/hint_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/config/generic/qos.go, pkg/util/qos/mem_enhancement.go
Enhancements
- cpu/memory plugin support memory enhancement numa_exclusive key/value
resolve #18
=> feat(qrm): support memory enhancement numa_exclusive

pkg/metaserver/config/manager.go
Features
Dynamic config manager support skip retry update config when skip failed initialization enable, because if skip failed initialization enable, it means that the agent can use default flags configuration to start and no need to retry, it can be updated later.
=> skip retry update config when skip failed initialization enable

pkg/agent/qrm-plugins/cpu/dynamicpolicy/allocation_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
Bug fixes
There are existing dedicated_cores sicar with empty owner pool name. It will influence sys advisor calculation. This pr is to ensure dedicated_cores owner pool non-empty.
=> fix(qrm): ensures dedicated_cores owner pool non-empty

cmd/katalyst-agent/app/options/eviction/eviction_base.go, pkg/agent/evictionmanager/eviction_resp_collector.go, pkg/agent/evictionmanager/manager.go, pkg/agent/evictionmanager/manager_test.go, pkg/config/agent/eviction/eviciton_base.go
Enhancements
When a new eviction plugin is added, user might not sure about the effect of this plugin. This pull request add a new configuration through which user can turn some certain plugins into dryrun mode. A plugin which in dryrun mode will only produce logs and metrics but not actually evict pods.
=> feat(eviction): support dryrun plugin

pkg/agent/evictionmanager/plugin/memory/rss_overuse.go, pkg/agent/evictionmanager/plugin/memory/rss_overuse_test.go, pkg/config/agent/eviction/memory_pressure_eviction_plugin.go, pkg/util/qos/mem_enhancement.go
Enhancements
this is a modification of pr [feat(eviction manager): support pod-level rss overuse evict](https://github.com/kubewharf/katalyst-core/pull/57). The plugin use pod memory request to calculate the threshold instead of pod memory limit.
=> feat(eviction): rss overuse eviction base on request

pkg/agent/sysadvisor/metacache/metacache.go
The modification of data struct for checkpoint will lead to hash not matched, we should create new checkpoint in this case.
Bug fixes
=> fix(sysadvisor): create new checkpoint if fetching it failed

pkg/metaserver/external/cgroupid/manager_linux.go
fix(external_mgr): fix adding cgroup id log format typo
=> fix(external_mgr): fix adding cgroup id log format typo

pkg/util/general/log.go, pkg/util/general/log_test.go
chore
format the logging styles in general util to export the entire pkg name
=> change log format to export the entire pkg name

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
As metricsFetcher.GetContainerMetric and cpuResourceAdvisor.update are called in separate goroutines, the latter may be executed before the former, resulting in obtaining empty metrics and falling back to using pod requests as estimated resources, which leads to a sharp decrease in headroom.
Bug fixes
=> fix: avoid fetching empty metrics

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/regulator/regulator.go
Enhancements
-->
exchange round and slowdown procedure in cpu regulator to ignore trivial ramp down of float number
#85
=> exchange round and slowdown in cpu regulator

cmd/katalyst-agent/app/options/eviction/memory_pressure_eviction_plugin.go, cmd/katalyst-agent/app/options/eviction/memory_pressure_eviction_plugin_test.go, pkg/agent/evictionmanager/plugin/memory/rss_overuse.go, pkg/agent/evictionmanager/plugin/memory/rss_overuse_test.go, pkg/config/agent/eviction/memory_pressure_eviction_plugin.go
Enhancements
A k8s cluster might contains many types of workloads, in them some might need to be evicted when rss over used than user expected meanwhile some might not need this feature. So we need a way to let user to select pods which can be evicted by rss overuse eviction plugin. This PR adds a new labels configuration which user can use it to select pods which can be evicted by rss overuse eviction plugin.
=> feat(eviciton): rss overuse eviction support pod filter

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go, pkg/agent/sysadvisor/types/types.go, pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
Enhancements
Add deadband for pid controller to avoid hunting during the control process.
=> add deadband for pid controller to avoid hunting

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go, pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
Bug fixes
fix sequential bugs that previous values are not effective in pid controller.
=> fix(sysadvisor): fix sequential bugs in pid controller

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/util/util.go
fix(qrm): fix numa_binding hint calculation
=> fix(qrm): fix numa_binding hint calculation

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go, pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go, pkg/agent/sysadvisor/types/consts.go, pkg/agent/sysadvisor/types/types.go
Enhancements
Increase rama policy robustness for several cases.
=> increase rama policy robustness

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go, pkg/agent/sysadvisor/types/types.go, pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_base.go, pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go, pkg/metaserver/metaserver.go, pkg/metaserver/spd/manager.go, pkg/metaserver/spd/manager_test.go, pkg/util/spd_indicator.go
Enhancements
cpu advisor should get pod indicator target from spd to support more granular cpu provisioning policies
=> cpu advisor support get pod indicator target from spd

pkg/agent/evictionmanager/plugin/memory/helper.go, pkg/agent/evictionmanager/plugin/memory/system_pressure.go, pkg/agent/evictionmanager/plugin/memory/system_pressure_test.go
Enhancements
system pressure eviction plugin use the diff value of kswapdsteal metric between two rounds of sync to check if the system is under memory pressure. But sometimes the metric is not updated as in time as we expected, it will lead to misjudgment. This PR checks the metric timestamp to prevent that misjudgment. When the metric timestamp is same with it in last round, we ignore this round.
=> enhancement(eviction): avoid misjudgment by checking metric timestamp

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_dedicated.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/agent/sysadvisor/types/types.go, pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
Enhancements
Add a headroom policy based on load and headroom assembler for scene with dedicated containers.
=> add headroom policy and assembler for dedicated

pkg/util/general/log.go, pkg/util/general/log_test.go
enhancements
switch the logging path as full by default
=> switch to full path of general logging

pkg/consts/common.go, pkg/consts/metric.go, pkg/metaserver/agent/metric/fake_metric.go, pkg/metaserver/agent/metric/malachite/cgroup/types.go, pkg/metaserver/agent/metric/malachite/system/types.go, pkg/metaserver/agent/metric/metric.go, pkg/metaserver/agent/metric/metric_calculation.go
enhancements
1. add metric for rss, cache and cpu usage for cgroup v2
2. expand the ability to add external metric
=> supplement metric and expand the ability to add external metric

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
Avoid the sender returning directly if the receiver is not waiting.
Bug fixes
=> fix(sysadvisor): set a buffer for the channel

pkg/custom-metric/store/data/cache.go, pkg/custom-metric/store/data/cache_test.go
bug fixes
filter out namespace that are not matched with the given one
=> filter out none-matched namespance in kcmas

pkg/controller/lifecycle/cnr_test.go, pkg/metaserver/agent/metric/malachite/cgroup/cgroup.go, pkg/metaserver/agent/metric/malachite/cgroup/cgroup_test.go, pkg/metaserver/agent/metric/malachite/client/client.go, pkg/metaserver/agent/metric/malachite/system/system.go, pkg/metaserver/agent/metric/malachite/system/system_test.go, pkg/metaserver/agent/metric/metric.go, pkg/metaserver/external/cgroupid/manager_linux_test.go
bug fixes/Enhancements
move malachite client from global variables to malachite fetcher to avoid testing races
=> move malachite client from global varibales to malachite fetcher

pkg/agent/evictionmanager/plugin/memory/helper.go, pkg/agent/evictionmanager/plugin/memory/helper_test.go, pkg/agent/evictionmanager/plugin/memory/numa_pressure.go, pkg/agent/evictionmanager/plugin/memory/numa_pressure_test.go, pkg/agent/evictionmanager/plugin/memory/rss_overuse.go, pkg/agent/evictionmanager/plugin/memory/system_pressure.go, pkg/agent/evictionmanager/plugin/memory/system_pressure_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/cache_reaper.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memset_binder.go, pkg/agent/sysadvisor/types/helper.go, pkg/metaserver/agent/metric/helper/consts.go, pkg/metaserver/agent/metric/helper/container.go, pkg/metaserver/agent/metric/helper/pod.go, pkg/metaserver/agent/metric/helper/system.go, pkg/util/machine/util.go
=> memory advisor plugins

cmd/katalyst-agent/app/agent/qrm/cpu_plugin.go, cmd/katalyst-agent/app/enableagents.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/utilcomponent/periodicalhandler/consts/consts.go, pkg/agent/utilcomponent/periodicalhandler/periodical_handler.go, pkg/agent/utilcomponent/periodicalhandler/periodical_handler_test.go, pkg/controller/spd/spd_test.go, pkg/util/process/http_test.go
feat(util): add periodical handlers util
=> feat(util): add periodical handlers util

cmd/katalyst-agent/app/options/global/metaserver.go, cmd/katalyst-controller/app/controller/lifecycle.go, cmd/katalyst-controller/app/options/lifecycle.go, pkg/config/agent/global/metaserver.go, pkg/config/controller/lifecycle.go, pkg/metaserver/agent/agent.go, pkg/metaserver/agent/cnc/fake_cnc.go, pkg/metaserver/metaserver_test.go
Enhancements
- Add a switch to disable cnc lifecycle controller
- Add a switch to disable metrics fetcher
=> feat(*): add switches to enable only components required for topology-aware scheduling

pkg/metaserver/agent/agent.go, pkg/metaserver/agent/agent_test.go
enhancements
support to register external object fecthers in metaserver
=> support to register external object fecthers in metaserver

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_util.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
Enhancements
refactor sysadvisor cpu headroom assembler by abstract the logic of util-based capacity estimation
=> refactor sysadvisor cpu headroom assembler by abstract the logic of util-based capacity estimation

cmd/base/options/generic.go, cmd/base/options/log.go, pkg/metrics/metrics-pool/otel_prom_metrics_mux.go, pkg/util/general/log.go
enhancements
provide the ability to set default logging package level
=> add flags to enable alert logging level

cmd/katalyst-agent/app/options/sysadvisor/qosaware/reporter/headroom_reporter.go, pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/cpu.go, pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/generic.go, pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/memory.go, pkg/config/agent/sysadvisor/qosaware/reporter/headroom_reporter.go, pkg/util/general/window.go, pkg/util/general/window_test.go
=> feat: introduce percentile aggregator for window sliding

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_test.go, pkg/metaserver/spd/manager.go, pkg/util/machine/machine.go, pkg/util/machine/machine_linux.go, pkg/util/machine/topology.go
… when reclaimed disabled
Bug fixes
=> fix(sysadvisor): set numa capicity as requirement of numabinding pods  when reclaimed disabled

pkg/controller/lifecycle/cnr.go
Bug fixes
Fix bug if cnr or cnc is not found in lister.
=> fix(controller): fix bug if cnr or cnc is not found in lister

cmd/katalyst-agent/app/options/global/metaserver.go, pkg/config/agent/global/metaserver.go, pkg/metaserver/agent/pod/kubelet.go, pkg/metaserver/agent/pod/pod.go
Features
Currently, katalyst fetches pods from the kubelet's read-only port, which may be not secure. This PR enables katalyst to fetch pods from the kubelet secure port.
This PR needs https://github.com/kubewharf/katalyst-core/pull/150 to be merged first.
=> feat(metaserver): support getting pods from kubelet secure port

pkg/agent/qrm-plugins/memory/dynamicpolicy/state/state.go
fix(qrm): use max NUMA allocatable to calculate min-needed NUMAs
=> fix(qrm): use max NUMA allocatable to calculate min-needed NUMAs

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_numa_exclusive.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/helper.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_test.go, pkg/agent/sysadvisor/types/cpu.go, pkg/agent/sysadvisor/types/helper.go, pkg/metaserver/spd/manager.go, pkg/util/general/common.go, pkg/util/general/common_test.go
=> feat: headroom policy for dedicated numa

cmd/katalyst-agent/app/options/dynamic/adminqos/reclaimedresource/reclaimedresource_base.go, pkg/agent/evictionmanager/eviction_resp_collector.go, pkg/agent/evictionmanager/manager.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pod_pool_getter.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_metric.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go, pkg/agent/qrm-plugins/util/util.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go, pkg/config/agent/dynamic/adminqos/reclaimedresource/reclaimedresource_base.go, pkg/util/machine/cpu.go
Enhancements
this pr support using dynamic threshold in load eviction plugin.
=> enhancement(eviction): load eviction support dynamic threshold

pkg/metaserver/agent/metric/malachite/client/client.go, pkg/metaserver/agent/metric/malachite/client/client_pod.go, pkg/metaserver/agent/metric/malachite/client/client_pod_test.go, pkg/util/cgroup/common/path.go
Bug fixes
when fetching metrics, we should trim the container id in pod spec (for malachite interface)
=> fix bugs to trim container id in pod spec

pkg/metaserver/agent/metric/malachite/client/client_pod.go, pkg/metaserver/agent/metric/malachite/client/client_pod_test.go
bug fixes
use container name instead of container id in metric store
=> store metric by pod-uid and container-name

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go, pkg/agent/sysadvisor/types/cpu.go
Enhancements
add stability status of region
=> add stability status of region

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton.go
Enhancements
add heartbeat for cpu pressure eviction plugin
=> enhancement(eviction): heartbeat in cpu pressure eviction plugin

pkg/agent/utilcomponent/periodicalhandler/periodical_handler.go, pkg/agent/utilcomponent/periodicalhandler/periodical_handler_test.go
Bug fixes
only one periodical handler get executed when there are multiple handlers.
=> fix(qrm): only one periodical handler get executed

pkg/controller/kcc/cnc_test.go, pkg/controller/kcc/kcc_test.go, pkg/controller/kcc/kcct.go, pkg/controller/kcc/kcct_test.go, pkg/controller/kcc/util/kcct.go, pkg/controller/spd/spd_test.go
Bug fixes
Fix bugs where modifying KCC or the target resource does not trigger updates for other KCCs or other target resources, requiring manual triggering of their updates.
=> fix kcc and target resource modify no trigger others update

pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/policy_control_knob_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
feat(qrm): modify memory control knob handler signature to add more utils convenient for handlers registered out of policy itself
=> feat(qrm): modify memory control knob handler signature to add more utils convenient for handlers registered out of policy itself

pkg/agent/evictionmanager/eviction_resp_collector.go, pkg/agent/evictionmanager/manager.go
Chores
the metric name contains "dryrun" but it will emit data when it's not in dryrun mode.
=> chores(eviction): rename metric

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go, pkg/consts/metric.go, pkg/metaserver/agent/metric/malachite/fetcher.go
If the value of "high_wmark_pages" in the system is large, "memory available" metric will be too low even zero from /proc/meminfo. We use "free+cache+buffer" as a substitute to figure this issue out.
Bug fixes
=> fix(sysadvisor): replace memory avaiable metric

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go
If buffer and reclaim group rss are both zero, qrm plugin will do nothing. In that case, the memory usage of reclaim group will not be throttled.
Enhancements
=> refactor(sysadvisor): set min reserved memory limit for reclaim group

cmd/katalyst-agent/app/options/global/metaserver.go, pkg/metaserver/metaserver_test.go, pkg/metaserver/spd/cache.go, pkg/metaserver/spd/fetcher.go, pkg/metaserver/spd/fetcher_test.go, pkg/metaserver/spd/manager_test.go
Bug fixes
Refactor the SPD fetcher to asynchronously retrieve SPD from a remote source, preventing it from blocking the service profiling manager during the profiling process.
=> refactor spd fetcher to async get spd from remote

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/metaserver/agent/metric/malachite/fetcher.go
Bug fixes/Enhancements
Skip update if container not ramping up with empty owner pool name exists
Fix sched wait metric to ms
=> fix advisor issues

cmd/katalyst-agent/main.go, cmd/katalyst-controller/main.go, cmd/katalyst-metric/main.go, cmd/katalyst-scheduler/main.go, cmd/katalyst-webhook/main.go, pkg/agent/qrm-plugins/network/staticpolicy/util.go, pkg/metaserver/agent/metric/malachite/fetcher.go
1. rand.Seed:
Deprecated: Programs that call Seed and then expect a specific sequence of results from the global random source (using functions such as Int) can be broken when a dependency changes how much it consumes from the global random source. To avoid such breakages, programs that need a specific result sequence should use NewRand(NewSource(seed)) to obtain a random generator that other packages cannot access.
2. rand.Read
Deprecated: For almost all use cases, crypto/rand.Read is more appropriate.
=> some rand functions are deprecated

pkg/agent/resourcemanager/fetcher/manager.go, pkg/agent/resourcemanager/fetcher/plugin/endpoint.go, pkg/agent/resourcemanager/fetcher/plugin/endpoint_test.go
…tReportContent return error
Bug fixes
Fixed the issue of data loss in the reporter plugin when the plugin is re-registered and the first call to GetReportContent returns an error.
=> Fix reporter plugin re-register data loss

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
Features/Bug fixes
Fallback from rama to canonical policy when reclaim is disabled.
Add buffer ratio for cpu estimation in canonical policy.
=> fallback to canonical when reclaim disabled; add buffer ratio for cpu estimation

docs/install-enhanced-k8s.md
katalyst's dependency on enhanced-k8s bumped from 1.24.6-kubewharf.4 to 1.24.6-kubewharf.7 since v0.3.0
update docs
=> chore(doc): update enhanced k8s installation guide

pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go, pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
=> fix(sysadvisor): assemble duplicate block

pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go, pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go
Bug fixes
GetTopologyZones returns an error if the list of pod resources is empty, because the pod resources server will return an empty pod resources list, but it is not empty in actual when the kubelet restarts.
=> GetTopologyZones return error if list pod resources empty

pkg/agent/evictionmanager/plugin/reclaimed_resources.go, pkg/agent/evictionmanager/plugin/resources.go
Bug fixes
ThresholdGetter of resource eviction support threshold not set
=> resource eviction ThresholdGetter support threshold not set

cmd/katalyst-agent/app/options/reporter/reporter_base.go, pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go, pkg/config/agent/reporter/reporter_base.go, pkg/controller/lifecycle/cnr.go
Bug fixes
When a Node is deleted, there may be remaining CNR (CustomNodeResource) objects without labels in cluster. This is because when a node is deleted, katalyst-agent creates a new CNR without labels, and the katalyst-controller is unable to GET the deleted node for patching labels. 
Additionally, during the periodic cleaning process in katalyst-controller, it lists CNRs with labels based on the NodeSelector from Informer initialization, excluding the CNR without labels created katalyst-agent. This causes the CNR to be unable to be cleaned up.
```
apiVersion: node.katalyst.kubewharf.io/v1alpha1
kind: CustomNodeResource
metadata:
name: 172.25.0.7
spec: {}
status: 
topologyPolicy: SingleNUMANodeContainerLevel
topologyZone:
...
```
This PR attempts to list all CNRs from the …
=> fix(controller): fix cnr residue when node deletion

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
bug fixes
fix bugs for isolation locking out in sysadvsior
=> fix set-pool-regions in sysadvisor: always use origin owner pool name

pkg/controller/kcc/cnc.go, pkg/controller/kcc/kcc.go, pkg/controller/kcc/kcct.go, pkg/controller/kcc/target/target_handler.go
Bug fixes
cnc/kcc/kcct controller should wait KatalystCustomConfigTargetHandler cache synced to aviod unexpectly behavior when cache no synced in restart.
=> fix KatalystCustomConfigTargetHandler to avoid cnc being cleared when cache no synced in restart

pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
Bug fixes
Avoid gc living containers' original owner pools.
=> fix(sysadvisor): avoid gc living containers' original owner pools

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
bug fixes
always set the min-value for isolation bound as 1 core
=> always set the min-value for isolation bound as 1 core

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware_test.go, pkg/agent/sysadvisor/types/memory.go, pkg/metaserver/agent/metric/malachite/fetcher.go
=> feat(sysadvisor): support numa aware memory headroom policy

pkg/consts/metric.go, pkg/metaserver/agent/metric/malachite/fetcher.go, pkg/util/metric/store.go
There are some metrics like iobusy/ioread/iowrite. They are  originated from [/proc/diskstats](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats) (their filed numbers are 13, 4, 8 respectively).
These metrics are like `counter type` in prom. Thus they need to be rated over time.
=> Add device io stat metrics

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware_test.go
Calculate memory headroom by numa free + reclaimed request. This modification helps scheduling based on real free memory resource, since central schedulers always schedule the pods based on request.
=> feat(sysadvisor): modify numa aware memory headroom policy

pkg/consts/metric.go, pkg/metaserver/agent/metric/malachite/fetcher.go, pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
Due to the sampling lag between katalyst(once per 5s) and malachite-core(once per 10s), there will be lots of "zero" value produced(70% for mem_read/write_bandwidth).
This work tries to fix the problem by setting rate metric only when the metric is updated.
For the previous version:
(Many "zero" cases could be seen in the three following moments.)
After Updating:
(No more "zero" values, but at the "start" moment basically. I did't upload them all, but I had checked about it.)
=> Fix calculation of rate metrics

pkg/custom-metric/store/local/local_store.go
Enhancements
To minimize the volume of logs generated when object retrieval fails during internal metric checks, particularly in instances where pods are created or deleted too frequently
=> increase the log level of getting object failed when check internal metric

pkg/custom-metric/provider/provider.go
enhancements
add metric to monitor the metric data latency
=> enhancement(kcmas): emit metric latency

pkg/controller/lifecycle/cnr_test.go, pkg/custom-metric/store/data/cache.go, pkg/custom-metric/store/data/cache_test.go, pkg/custom-metric/store/data/internal.go, pkg/custom-metric/store/data/types/aggragated.go, pkg/custom-metric/store/data/types/util.go, pkg/custom-metric/store/local/local_store.go, pkg/custom-metric/store/remote/remote_store.go
Bug fixes
fix aggregator metric
=> decode metric list according to metric name whether is aggregator metric

pkg/custom-metric/store/data/cache.go, pkg/custom-metric/store/data/types/aggragated.go
Bug fixes
add store metric length metrics and fix aggregator window
=> fix window seconds

cmd/base/context.go, cmd/katalyst-metric/app/options/collector.go, pkg/config/metric/collector.go, pkg/custom-metric/collector/prometheus/collector_promethes.go, pkg/custom-metric/collector/prometheus/collector_test.go, pkg/custom-metric/collector/prometheus/scrape.go, pkg/custom-metric/collector/prometheus/scrape_test.go
Enhancements
metric collector scrape with basic auth
=> feature(kcmas): scrape with basic auth

pkg/util/metric/store_util.go
=> check coreCount within AggregateCoreMetric

pkg/agent/sysadvisor/plugin/inference/inference.go, pkg/agent/sysadvisor/plugin/inference/inference_test.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein_test.go
feat(advisor): support disable registered model result fetcher
=> feat(advisor): support disable registered model result fetcher

cmd/base/context.go, cmd/base/options/auth.go, cmd/base/options/generic.go, cmd/katalyst-agent/app/agent.go, cmd/katalyst-agent/app/agent/eviction.go, pkg/config/generic/auth.go, pkg/config/generic/generic_base.go, pkg/util/process/http.go, pkg/util/process/http_test.go
Enhancements
support non-strict authentication
=> feat(http): non-strict authentication

pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go, pkg/agent/sysadvisor/types/helper.go
1. only update indicators when enbale borwein and rama in use 
2. support resetting indicator offset
3. use matacache instead of metaserver to get request containers to inference for
=> feat(advisor): borwein fix & enhancement

pkg/custom-metric/collector/prometheus/collector_promethes.go, pkg/custom-metric/collector/prometheus/scrape.go
Enhancements
kcams add collector scrape out of date metrics
=> kcams add collector scrape out of date metrics

cmd/katalyst-webhook/app/webhook.go, cmd/katalyst-webhook/app/webhook/mutating/node.go, pkg/util/native/resources.go, pkg/util/native/resources_test.go, pkg/webhook/mutating/node/allocatable_mutator.go, pkg/webhook/mutating/node/node.go, pkg/webhook/mutating/node/node_test.go
Features
add a node mutatingwebhook.
this webhook hijack node.status updating requests, amplify node allocatable and capacity by node overcommitment annotations, which supports node resource overcommitment without users' awareness
#214
=> feat(overcommit): add node overcommit webhook

cmd/base/context_fake.go, cmd/katalyst-controller/app/controller/overcommit.go, cmd/katalyst-controller/app/enablecontrollers.go, cmd/katalyst-controller/app/options/controller.go, cmd/katalyst-controller/app/options/overcommit.go, pkg/client/control/noc.go, pkg/client/control/node.go, pkg/config/controller/controller_base.go, pkg/config/controller/overcommit.go, pkg/controller/overcommit/node/handler.go, pkg/controller/overcommit/node/matcher/matcher.go, pkg/controller/overcommit/node/matcher/matcher_test.go, pkg/controller/overcommit/node/matcher/sorter.go, pkg/controller/overcommit/node/node.go, pkg/controller/overcommit/node/node_test.go
Features
add nodeOvercommit controller
nodeOvercommit controller watches nodeOvercommitConfigs and nodes, matches node and configs by rules in nodeOvercommitConfigs, and then update node overcommit annotations.
https://github.com/kubewharf/katalyst-core/issues/214
katalyst-api pr: https://github.com/kubewharf/katalyst-api/pull/34
=> feat(overcommit): add nodeovercommit controller

cmd/katalyst-metric/app/options/store.go, pkg/config/generic/service_discovery.go, pkg/config/metric/store.go, pkg/custom-metric/provider/provider_test.go, pkg/custom-metric/store/remote/remote_store.go, pkg/custom-metric/store/remote/sharding.go, pkg/util/service-discovery/dummy_sd.go, pkg/util/service-discovery/interface.go, pkg/util/service-discovery/pod_single_port_sd.go, pkg/util/service-discovery/service_single_port_sd.go, pkg/util/service-discovery/service_single_port_sd_test.go
enhancements
add standard framework to support multiple service discovery implementations
=> add standard framework for service discovery

pkg/custom-metric/provider/provider.go, pkg/custom-metric/store/data/cache.go, pkg/custom-metric/store/data/cache_test.go, pkg/custom-metric/store/data/internal.go, pkg/custom-metric/store/data/types/aggragated.go, pkg/custom-metric/store/data/types/series.go, pkg/metrics/tag_wrapper_metrics.go, pkg/util/general/deepcopy.go
Enhancements
1. fix kcmas data latency monitor
2. some performance optimization
=> perf(kcmas): performance optimization

cmd/base/context.go, cmd/base/context_fake.go, go.mod, go.sum, pkg/client/genericclient.go
Enhancements
add kube-aggregator client
=> chore(generic): add kube-aggregator client

pkg/metaserver/agent/metric/malachite/fetcher.go, pkg/metaserver/agent/metric/malachite/types/system.go
=> feat(metaserver): add node cpu usage ratio metric

cmd/katalyst-metric/app/metric.go, cmd/katalyst-metric/app/mode/collect.go, cmd/katalyst-metric/app/options/mock.go, cmd/katalyst-metric/app/options/options.go, pkg/config/metric/metric_base.go, pkg/config/metric/mock.go, pkg/custom-metric/mock/mock_collector.go, pkg/custom-metric/mock/mock_store.go, pkg/custom-metric/mock/utils.go, pkg/custom-metric/mock/utils_test.go
Enhancements
kcmas supports generating mock data for pressure test.
=> [WIP]feat(kcmas):mock collector

pkg/config/metric/store.go, pkg/custom-metric/provider/provider_test.go, pkg/custom-metric/store/data/cache.go, pkg/custom-metric/store/data/cache_test.go, pkg/custom-metric/store/data/internal/internal.go, pkg/custom-metric/store/local/local_store.go
Performance
optimize the lock logic in kcmas store.
=> performance(kcmas): lock optimize

pkg/metaserver/agent/metric/malachite/fetcher.go, pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
=> optimize(metric): optimize calculation of counter rate

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
=> enhancement(sysadvisor): export region reclaimable info as non-reclaim when dedicated_cores can not be co-located with reclaimed_cores

cmd/katalyst-metric/app/options/store.go, pkg/config/metric/store.go, pkg/custom-metric/provider/provider.go, pkg/custom-metric/provider/provider_test.go, pkg/custom-metric/store/data/cache.go, pkg/custom-metric/store/data/cache_test.go, pkg/custom-metric/store/local/local_store.go
Enhancements
this PR supports index when query from custom metrics.
=> enhancement(kcmas): object index

pkg/agent/qrm-plugins/network/state/util.go
Enhancements
Print out NIC info when initializing qrm network plugin
=> Print out NIC info upon qrm network plugin initialization

pkg/custom-metric/store/data/cache.go, pkg/custom-metric/store/data/cache_test.go, pkg/custom-metric/store/data/object_store.go, pkg/custom-metric/store/data/object_store_test.go, pkg/custom-metric/store/local/local_store.go
Enhancements
support bucket object store in kcmas
=> enhancement(kcmas): bucket object store

docs/proposals/scheduling/20220913-katalyst-scheduler-design.md, examples/scheduler-policy-binpack.yaml, examples/scheduler-policy-custom.yaml, examples/scheduler-policy-spread.yaml
If  do not close the NodeResourcesFit, it will cause the katalyst-scheduler to schedule the reclaimed core pod in the Filter stage.
#331
=> doc: some fixes to examples and proposals for the reclaimed core pod cannot be scheduled

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware_test.go
calculate memory headroom by system free, reclaimed-core container request and system watermark.
=> refine numa-aware memory headroom policy

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_dedicated.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/helper.go
=> enhancement(sysadvisor): update region info atomically

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
bug fixes
fix bugs for isolation region be created multiple times
=> fix bugs for creating isolation region multiple times

pkg/controller/spd/spd.go, pkg/controller/spd/spd_test.go, pkg/custom-metric/store/data/object_store.go, pkg/util/spd.go, pkg/webhook/mutating/pod/spd_ref_mutator.go
=> enhancement(spd): get spd by workload's name

cmd/katalyst-agent/app/options/qrm/memory_plugin.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/const.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux_test.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/utils_linux.go, pkg/agent/qrm-plugins/memory/memory.go, pkg/config/agent/qrm/memory_plugin.go, pkg/consts/metric.go, pkg/metaserver/agent/metric/malachite/fetcher.go, pkg/metaserver/agent/metric/malachite/types/cgroup.go, pkg/util/cgroup/common/types.go, pkg/util/cgroup/manager/v1/fs_linux.go
What type of PR is this?
Features
What this PR does / why we need it:
The feature provides the unified solution for TCP memory limitation in cgroup and global level.
Which issue(s) this PR fixes:
In our production environment, there is a critical case where certain services heavily consumed tcpmem(cgroupv1 pods with default setting have unlimited tcpmem), causing the global tcpmem to reach the limitation. As a result, the network performance of the entire machine was crash.
Special notes for your reviewer:
The feature includes 3 parts:
1, Set global tcpmem limit by changing net.ipv4.tcp_mem.
The default value is 20% of host toal memory.
2, Do nothing under cgroupv2.
3, Set pod tcpmem limit under cgroupv1.
The default value is same with memory.limit_in_bytes.
=> feat(sockmem-plugin): unified solution for TCP memory limitation #365

pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
I tried to fix negative numbers by calculating counter delta in `uint64CounterDelta`.
However more massive numbers emerged. I guess `math.MaxUint64 - previous + current` is the root cause.
The upper bound for each counter is not available now. So, I made some small change here. Which is returning 0 directly when `previous counter value > current counter value`.
=> updating counterDelta func

pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux_test.go
Bug Fix
bug fix: fix unit test race in sockmem plugin
unit test race in sockmem plugin, plz see following as reference:
WARNING: DATA RACE
Read at 0x000004feb178 by goroutine 84:
github.com/kubewharf/katalyst-core/pkg/agent/qrm-plugins/memory/handlers/sockmem.setCg1TCPMem()
/runner/_work/katalyst-core/katalyst-core/pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux.go:71 +0x84
github.com/kubewharf/katalyst-core/pkg/agent/qrm-plugins/memory/handlers/sockmem.TestSetCg1TCPMem()
/runner/_work/katalyst-core/katalyst-core/pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux_test.go:301 +0xc4
testing.tRunner()
/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x213
testing.(*T).Run.func1()
/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x47 …
=> fix unit test race in sockmem plugin

pkg/agent/evictionmanager/podkiller/killer.go, pkg/agent/evictionmanager/podkiller/killer_test.go, pkg/agent/evictionmanager/podkiller/podkiller.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/const.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux_test.go, pkg/agent/qrm-plugins/util/util.go, pkg/agent/sysadvisor/metacache/metacache.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/util/asyncworker/async_workers.go, pkg/util/asyncworker/async_workers_test.go, pkg/util/asyncworker/helpers.go, pkg/util/asyncworker/types.go, pkg/util/cgroup/manager/cgroup.go
enhancements
add more metrics and tags for eviction and qrm logic
=> add metrics for eviction and handlers

pkg/util/service-discovery/service_single_port_sd.go
Bug fixes
When more than one store instances are scheduled on same node, only one instance can be used.
=> fix(kcmas): missing store instance in same node

pkg/util/spd_baseline.go, pkg/util/spd_baseline_test.go
=> fix(spd): baseline checking

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/util/cgroup/manager/cgroup.go, pkg/util/cgroup/manager/cgroup_test.go
feat(qrm): adapt drop cache operation with cgv2
=> feat(qrm): adapt drop cache operation with cgv2

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression_test.go
Enhancements
refactor cpu pressure eviction framework to make the eviction strategy be an independent eviction plugin, which is more friendly to metrics observation
=> refactor cpu pressure eviction framework

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/nativepolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/util/native/pod_sorter.go, pkg/util/native/resources.go
=> support custom GetCPUQuantity and GetMemoryQuantity func

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go, pkg/util/general/sorter.go, pkg/util/native/pod_sorter.go, pkg/util/native/pod_sorter_test.go
Bug fixes
suppression eviction add PodUniqKeyCmpFunc to make sure the sort result is stable
=> suppression eviction add PodUniqKeyCmpFunc to make sure the sort result is stable

pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util_test.go, pkg/config/generic/qos.go
feat(qrm): support getting specified pool name in QoS conf
=> feat(qrm): support getting specified pool name in QoS conf

pkg/agent/resourcemanager/fetcher/system/systemplugin.go
Enhancements
support report numa count to kcnr
=> support report numa count to kcnr

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_isolation.go, pkg/agent/sysadvisor/plugin/qosaware/qos_aware.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_load.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go, pkg/agent/sysadvisor/plugin/qosaware/server/base_server.go, pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go, pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go, pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go, pkg/agent/sysadvisor/plugin/qosaware/server/memory_server_test.go, pkg/agent/sysadvisor/plugin/qosaware/server/server.go, pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
Enhancements
isolation support non-exclusive
=> isolation support non-exclusive

pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein_test.go
Adding current timestamp_in_second to borwein get feature functions. Which could help feature data provider cache data.
=> add timestamp to get feature function

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/plugins/common.go, cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/plugins/memory_provisioner.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/const.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/policy_control_knob_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/memory.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/memory_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/provisioner/memory_provisioner.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/provisioner/policy/policy.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/provisioner/policy/policy_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/provisioner/policy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/provisioner/policy/policy_canonical_test.go, pkg/agent/sysadvisor/types/memory.go, pkg/config/agent/sysadvisor/qosaware/resource/memory/plugins/memory_provisioner.go, pkg/util/machine/topology.go, pkg/util/machine/topology_test.go
=> feat(sysadvisor): Refined NUMA-granularity Memory Management and Control Framework

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go
feat(advisor): add indicator offset metric for borwein controller
=> feat(advisor): add indicator offset metric for borwein controller

pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/node.go, pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go, pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod_test.go, pkg/metaserver/agent/metric/malachite/fetcher.go
bug fixes
fix bugs for malachite fetcher race condition with kcmas
=> fix race conditions for malachite

pkg/metaserver/agent/metric/malachite/fetcher.go, pkg/util/syntax/lock.go, pkg/util/syntax/lock_test.go
enhancements
add locking framework to detact potential deadlocks
=> add locking framework to detect potential deadlocks

cmd/katalyst-agent/app/options/sysadvisor/inference/inference_plugin.go, pkg/consts/metric.go, pkg/metaserver/agent/metric/malachite/fetcher.go, pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
There are some metrics have been calculating incorrectly. Try to fix them in the pr.
1. Rename MetricCPUNR`d`PeriodRateContainer to MetricCPUNRPeriodRateContainer.
2. Try to assign l3_misses with OcrReadDrams when L3Misses is 0.
3. Fill the lost metrics like MetricCPUThrottledTimeContainer/MetricCPUNrThrottledContainer/MetricCPUNrPeriodContainer in the case of v2 cgroups.
4. Optimizing the calculation for MetricNetTcpRecvPacketsContainer/MetricNetTcpSendPacketsContainer/MetricNetTcpRecvBytesContainer/MetricNetTcpSendBytesContainer.
=> fix container metrics

cmd/katalyst-agent/app/agent/orm.go, cmd/katalyst-agent/app/enableagents.go, cmd/katalyst-agent/app/options/options.go, cmd/katalyst-agent/app/options/orm/orm_base.go, go.mod, pkg/agent/resourcemanager/outofband/checkpoint.go, pkg/agent/resourcemanager/outofband/checkpoint/checkpoint.go, pkg/agent/resourcemanager/outofband/checkpoint/checkpoint_test.go, pkg/agent/resourcemanager/outofband/checkpoint_test.go, pkg/agent/resourcemanager/outofband/endpoint/consts.go, pkg/agent/resourcemanager/outofband/endpoint/endpoint.go, pkg/agent/resourcemanager/outofband/endpoint/endpoint_test.go, pkg/agent/resourcemanager/outofband/endpoint/resource_plugin_stub.go, pkg/agent/resourcemanager/outofband/executor/executor.go, pkg/agent/resourcemanager/outofband/executor/executor_test.go, pkg/agent/resourcemanager/outofband/manager.go, pkg/agent/resourcemanager/outofband/manager_test.go, pkg/agent/resourcemanager/outofband/metamanager/manager.go, pkg/agent/resourcemanager/outofband/metamanager/manager_test.go, pkg/agent/resourcemanager/outofband/metamanager/types.go, pkg/agent/resourcemanager/outofband/pluginhandler.go, pkg/agent/resourcemanager/outofband/pod_resource.go, pkg/agent/resourcemanager/outofband/pod_resource_test.go, pkg/agent/resourcemanager/outofband/types.go, pkg/config/agent/agent_base.go, pkg/config/agent/orm/orm_base.go, pkg/util/cgroup/common/path.go, pkg/util/cgroup/manager/fake_manager.go, pkg/util/native/resources.go
Features
orm(outofband-resource-manager) supports dynamically allocating resources to pods with different QoS asynchronously through a bypass approach, without relying on intrusive changes to kubelet.
The current version supports shared_cores and reclaimed_cores pool.
#430
=> feat(orm): support outofband-resource-manager

pkg/agent/sysadvisor/plugin/inference/inference.go, pkg/agent/sysadvisor/plugin/inference/inference_test.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein_test.go, pkg/agent/sysadvisor/plugin/inference/models/borwein/types/types.go, pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/model.go, pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go, pkg/metaserver/agent/metric/malachite/fetcher.go, pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
Emitting model inference result of pod to kcmas. Which could help centric components leverage the output to work on optimization stuff.
=> add model ouput to kcmas

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
fix(qrm): fix panic when handleAdvisorCPUSetMems got nil allocationInfo, add robustness
=> fix(qrm): fix panic when handleAdvisorCPUSetMems got nil allocationInfo, add robustness

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware_test.go
=> refactor(sysadvisor): consider per numa memory reserved

cmd/katalyst-agent/app/options/orm/orm_base.go, pkg/agent/orm/checkpoint_test.go, pkg/agent/orm/endpoint/endpoint.go, pkg/agent/orm/manager.go, pkg/agent/orm/manager_test.go, pkg/agent/orm/pluginhandler.go, pkg/agent/orm/pod_resource.go, pkg/agent/orm/topology/manager.go, pkg/agent/orm/topology/manager_test.go, pkg/agent/orm/topology/policy.go, pkg/agent/orm/topology/policy_best_effort.go, pkg/agent/orm/topology/policy_best_effort_test.go, pkg/agent/orm/topology/policy_none.go, pkg/agent/orm/topology/policy_none_test.go, pkg/agent/orm/topology/policy_numeric.go, pkg/agent/orm/topology/policy_numeric_test.go, pkg/agent/orm/topology/policy_restricted.go, pkg/agent/orm/topology/policy_restricted_test.go, pkg/agent/orm/topology/policy_single_numa_node.go, pkg/agent/orm/topology/policy_single_numa_node_test.go, pkg/agent/orm/topology/policy_test.go, pkg/agent/orm/topology/topologyhint.go, pkg/util/bitmask/bitmask.go, pkg/util/bitmask/bitmask_test.go
Enhancements
Add topology manager with policies(none, best-effort, restrict, single-numa-node, numeric) for ORM.
Pods added by ORM should GetTopologyHints from QRM plugins and generated a best hint by topology manager policy before allocate resource. Dedicated-cores pods with numaBinding can be allocated resource by this way in ORM.
=> feat(ORM): outofband topology manager

pkg/util/asyncworker/async_workers.go, pkg/util/asyncworker/helpers.go, pkg/util/asyncworker/types.go
feat(async_work): add async work duration and panic metrics
=> feat(async_work): add async work duration and panic metrics

pkg/agent/evictionmanager/manager.go
Features
Add Pod QoS into metric tag
=> feat(eviction): add qos tag

cmd/katalyst-agent/app/options/global/metaserver.go
Enhancements
Disable metrics expire checking by default
=> fix(metaserver): disalbe metrics expire check by default

cmd/katalyst-agent/app/options/dynamic/adminqos/eviction/eviction_base.go, cmd/katalyst-agent/app/options/dynamic/adminqos/eviction/rootfs_pressure_eviction.go, pkg/config/agent/dynamic/adminqos/eviction/rootfs_pressure_eviction.go
Features
Support rootfs eviction options.
=> feat(eviction): add rootfs eviction options

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
=> refactor(sysadvisor): add idle status for region

pkg/util/vpa.go, pkg/util/vpa_test.go
…thout setting limit
Bug fixes
vpa In recreate update mode, webhook will update the recommended request to the newly created pod. Before updating, it will check whether request is less than limit. 
However, if limit is not set, an error will be reported and the update cannot be made.
This pr is designed to fix this bug
=> fix(vpa webhook): fix vpa webhook could not update request for pod without setting limit

pkg/util/cgroup/common/types.go, pkg/util/cgroup/manager/v1/fs_linux.go, pkg/util/cgroup/manager/v1/fs_linux_test.go, pkg/util/cgroup/manager/v2/fs_linux.go, pkg/util/cgroup/manager/v2/fs_linux_test.go
setting memory.low/min in ApplyMemory()
descriptions for memory.low & memory.min:   
memory.low: cgroup memory that will not be reclaimed in soft_limit_reclaim phase of kswapd
memory.min: cgroup memory that can never be reclaimed by kswapd
Enhancements
Provide the interfaces of memory.low/min to help users to set.
None.
Through these new interfaces, we can set a series of special settings for the critical services, such as katalyst, malachite.
=> feat(cgroup): setting memory.low/min in ApplyMemory()

cmd/katalyst-agent/app/options/sysadvisor/qosaware/qos_aware_plugin.go, cmd/katalyst-agent/app/options/sysadvisor/qosaware/reporter/node_metric_reporter.go, cmd/katalyst-agent/app/options/sysadvisor/qosaware/reporter/reporter.go, pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go, pkg/agent/resourcemanager/reporter/cnr/cnrreporter_test.go, pkg/agent/sysadvisor/plugin/qosaware/qos_aware.go, pkg/agent/sysadvisor/plugin/qosaware/qos_aware_test.go, pkg/agent/sysadvisor/plugin/qosaware/reporter/headroom_reporter.go, pkg/agent/sysadvisor/plugin/qosaware/reporter/headroom_reporter_test.go, pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter.go, pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter_test.go, pkg/agent/sysadvisor/plugin/qosaware/reporter/reporter_interface.go, pkg/agent/sysadvisor/types/reporter.go, pkg/config/agent/sysadvisor/qosaware/qos_aware_plugin.go, pkg/config/agent/sysadvisor/qosaware/reporter/node_metric_reporter.go, pkg/config/agent/sysadvisor/qosaware/reporter/reporter.go, pkg/util/cnr.go, pkg/util/syntax/reflect.go
=> feat: support node metrics reporter

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/util.go, pkg/agent/qrm-plugins/cpu/nativepolicy/policy.go, pkg/agent/qrm-plugins/cpu/nativepolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/cpu/nativepolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/network/staticpolicy/policy.go, pkg/agent/qrm-plugins/util/util.go, pkg/agent/qrm-plugins/util/util_test.go
refine(qrm): calculate pool size with much accuracy
=> refine(qrm): calculate pool size with much accuracy

go.mod, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64_test.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/util_unsupported.go
Enhancements
Use move_page syscall intead of migrate_pages to migrate numa memory
-  move_page syscall has more more fine-grained locks  than migrate_page
-  control the number of pages migrated each time to ensure the move latency is within a acceptable range (20ms).
- reduce the blocked time for the process migrated，block time is dropped from minutes to milliseconds.
=> feat(qrm): use move_pages syscall to migrate numa memory

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/util.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/util_test.go
fix(qrm): fix advisor drop cache handler missing nbytes parameter
=> fix(qrm): fix advisor drop cache handler missing nbytes parameter

pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go, pkg/agent/resourcemanager/fetcher/kubelet/topology/filter.go, pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go, pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go, pkg/controller/spd/spd_test.go, pkg/util/cnr_topology.go, pkg/util/qos/mem_enhancement.go
Enhancements
kubelet reporter plugin support report shared_cores with numa_binding pod, and add GenericPodResourcesFilter to filter out cpu and memory of shared_cores without numa_binding pod.
=> kubelet reporter plugin support shared_cores with numa_binding pod

pkg/util/cgroup/common/path.go, pkg/util/cgroup/common/types.go
Bug fixes
This PR uses multiple cgroup subsystem to detect real cgroup path in case one of them does't exist.
=> feat(meatserver): use multiple subsystems to detect cgroup path

cmd/base/context.go, cmd/base/healthz.go, cmd/base/options/generic.go, cmd/katalyst-agent/app/agent.go, pkg/agent/qrm-plugins/cpu/consts/consts.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/memory/consts/consts.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/oom/const.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_async_handler.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/const.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux.go, pkg/agent/qrm-plugins/memory/memory.go, pkg/agent/resourcemanager/fetcher/manager.go, pkg/agent/resourcemanager/fetcher/manager_healthz.go, pkg/agent/resourcemanager/fetcher/manager_test.go, pkg/agent/utilcomponent/periodicalhandler/periodical_handler.go, pkg/config/generic/generic_base.go, pkg/util/general/healthz.go
Features
refine healthz interface, aggregate all exception info to healthz api.
=> feat(qrm): refine healthz

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_balancer.go
Bug fixes
1. fixs the bug that the pod will never be evicted when `GetAdvice` is called prior to `GetEvictPods`.
2. don't skip the evicted pod when finding the balanced pod since eviction might not succeed.
=> fix(sysadvisor): numa balancer miss eviction

pkg/metaserver/spd/manager.go, pkg/metaserver/spd/manager_test.go
=> fix ServiceExtendedIndicator return nil object

cmd/katalyst-agent/app/options/eviction/eviction_base.go, pkg/agent/evictionmanager/eviction_resp_collector.go, pkg/agent/evictionmanager/manager.go, pkg/config/agent/eviction/eviciton_base.go
Enhancements
Support add specified pod labels into metric selectors.
=> feat(eviction): add eviction pod metric labels

pkg/controller/spd/spd.go, pkg/controller/spd/spd_test.go, pkg/util/native/object.go
=> spd: get qos Level by pod and its annotations

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go, pkg/metaserver/agent/metric/fake_metric.go, pkg/metaserver/agent/metric/metric_impl.go, pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go, pkg/metaserver/agent/metric/types/metric.go, pkg/util/metric/store.go
Enhancements
The current memory protection mechanism is achieved by setting the memory limit of the Besteffort group to avoid memory overflows. However, when calculating the limit, the cache of high-priority services is considered as reclaimable, so that direct memory reclamation can still be triggered when memory bursting. This MR refactors the calculation logic. Firstly, we calculates the safety memory upper limit for each available NUMA node, and then sums them up to obtain the result. The upper limit for each NUMA node is calculated as followed: NUMA free memory + Besteffort group memory used  on the NUMA node - reserved memory.
=> refactor(sysadvisor): refine memory guard

cmd/katalyst-agent/app/options/qrm/io_plugin.go, pkg/agent/qrm-plugins/io/handlers/iocost/const.go, pkg/agent/qrm-plugins/io/handlers/iocost/iocost_linux.go, pkg/agent/qrm-plugins/io/handlers/iocost/iocost_linux_test.go, pkg/agent/qrm-plugins/io/handlers/iocost/utils.go, pkg/agent/qrm-plugins/io/handlers/iocost/utils_test.go, pkg/agent/qrm-plugins/io/staticpolicy/policy.go, pkg/config/agent/qrm/io_plugin.go, pkg/util/cgroup/manager/v2/fs_linux.go
Features
This patch provied the feature of io.cost setting.
In production area, some critical services and online pods were affected by busy io.
This patch provieded the io qos feature
None
=> feat: adding support to io.cost setting

cmd/katalyst-agent/app/options/qrm/io_plugin.go, pkg/agent/qrm-plugins/io/handlers/ioweight/const.go, pkg/agent/qrm-plugins/io/handlers/ioweight/ioweight_linux.go, pkg/agent/qrm-plugins/io/handlers/ioweight/ioweight_linux_test.go, pkg/agent/qrm-plugins/io/staticpolicy/policy.go, pkg/config/agent/qrm/io_plugin.go
Features
This patch provied the feature of io.weight setting.
In production area, some critical services and online pods were affected by busy io.
None.
=> feat: adding support to io.weight setting 

pkg/util/cgroup/manager/v1/fs_linux.go, pkg/util/cgroup/manager/v2/fs_linux.go
-1 is valid for memory.limit_in_bytes
Enhancements
=> util(cgroup): relax constraints

.github/workflows/ci.yml, cmd/katalyst-controller/app/options/spd.go, pkg/config/controller/spd.go, pkg/consts/spd.go, pkg/controller/kcc/cnc.go, pkg/controller/kcc/util/kcct.go, pkg/controller/lifecycle/agent-healthz/handler/handler_generic.go, pkg/controller/lifecycle/agent-healthz/healthz_controller.go, pkg/controller/lifecycle/agent-healthz/helper/healthz_check.go, pkg/controller/lifecycle/cnr_test.go, pkg/controller/spd/cnc.go, pkg/controller/spd/cnc_test.go, pkg/controller/spd/spd.go, pkg/controller/spd/spd_baseline.go, pkg/controller/spd/spd_test.go, pkg/metaserver/spd/cache.go, pkg/metaserver/spd/fetcher.go, pkg/metaserver/spd/fetcher_test.go, pkg/util/cnc.go, pkg/util/native/object.go, pkg/util/native/pod_finder.go, pkg/util/spd.go, pkg/util/spd_test.go, pkg/webhook/mutating/pod/spd_ref_mutator.go
Features
To minimize high query-per-second (QPS) rates from agents to the API server, we implement a Custom Node Config (CNC) to store Service Profile Descriptor (SPD) information needed by the node, acting as an SPD cache. Agents periodically fetch the CNC, and will only attempt to update the local SPD cache from the API server if there's a mismatch between the hash of the local cache's SPD and the SPD information in the CNC.
=> spd support cnc cache

cmd/katalyst-agent/app/options/metaserver/metaserver.go, pkg/config/agent/metaserver/agent.go, pkg/metaserver/agent/metric/metric_impl.go, pkg/metaserver/agent/metric/metric_provisoner.go, pkg/metaserver/agent/metric/provisioner/cgroup/provisioner.go, pkg/metaserver/agent/metric/provisioner/kubelet/provisioner.go, pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go, pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go, pkg/metaserver/agent/metric/provisioner/rodan/client/client.go, pkg/metaserver/agent/metric/provisioner/rodan/client/client_node.go, pkg/metaserver/agent/metric/provisioner/rodan/client/client_node_test.go, pkg/metaserver/agent/metric/provisioner/rodan/client/client_pod.go, pkg/metaserver/agent/metric/provisioner/rodan/client/client_pod_test.go, pkg/metaserver/agent/metric/provisioner/rodan/provisioner.go, pkg/metaserver/agent/metric/provisioner/rodan/provisioner_test.go, pkg/metaserver/agent/metric/provisioner/rodan/types/consts.go, pkg/metaserver/agent/metric/provisioner/rodan/types/types.go, pkg/metaserver/agent/metric/provisioner/rodan/types/types_test.go
Enhancements
Add a metric provisioner that requests metrics from rodan(metrics collector like malachite).
Add a config which allows metric fetcher to init provisioners according to the provisioner name list. Malachite and kubelet are used by default, and rodan is used in private scenarios.
=> feat(metric): add rodan metric provisioner

cmd/katalyst-agent/app/options/dynamic/dynamic_base.go, cmd/katalyst-agent/app/options/dynamic/tmo/tmo_base.go, cmd/katalyst-agent/app/options/dynamic/tmo/tmodefault/tmo_default_config.go, cmd/katalyst-agent/app/options/global/base.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/const.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/util/consts.go, pkg/agent/qrm-plugins/util/util.go, pkg/agent/sysadvisor/plugin/qosaware/qos_aware.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/helper.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_offloading.go, pkg/config/agent/dynamic/crd/dynamic_crd.go, pkg/config/agent/dynamic/dynamic_base.go, pkg/config/agent/dynamic/tmo/tmo_base.go, pkg/config/agent/global/base.go, pkg/consts/common.go, pkg/consts/metric.go, pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go, pkg/metaserver/agent/metric/provisioner/malachite/types/common.go, pkg/util/cgroup/common/types.go, pkg/util/cgroup/manager/cgroup.go, pkg/util/cgroup/manager/cgroup_test.go, pkg/util/cgroup/manager/v1/fs_linux.go, pkg/util/cgroup/manager/v2/fs_linux.go, pkg/util/general/common.go, pkg/util/metric/store.go
Enhancements
This feature provides ability to trigger memory offload to save memory without performance downgrade, saved memory could be used for deploy more reclaimed_cores workloads to raise CPU utilization.
=> feat: Add TransparentMemoryOffloading plugin to trigger memory offloading

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/util/util.go, pkg/util/asyncworker/async_workers.go, pkg/util/cgroup/manager/cgroup.go, pkg/util/cgroup/manager/cgroup_test.go
feat(qrm): use async worker to set extra cg mem limit to avoid thread stucking
=> feat(qrm): use async worker to set extra cg mem limit to avoid thread stucking

pkg/controller/overcommit/node/node.go, pkg/controller/overcommit/node/node_test.go, pkg/util/native/resources.go
Bug fixes
Memory value overflow when node patch a large memory allocatable in status, eg. '1Ei'.
Convert memory value by quantity.Value which can cover larger values than MilliValue.
=> fix: convert memory by quantity.Value in overcommit controller

examples/reclaimed-large-pod.yaml
Others
As the [katalyst docs](https://gokatalyst.io/docs/getting-started/colocation-quick-start/) description, katalyst provides a yaml to create  reclaimed-large-pod, but the yaml has a format error that caused the pod creation to fail.
Test result after fixed:
=> fix reclaimed-large-pod.yaml in examples

pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go
fix(borwein): use indicator original value when it cannot be updated by borwein
=> fix(borwein): use indicator original value when it cannot be updated by borwein

pkg/agent/evictionmanager/manager.go, pkg/agent/evictionmanager/plugin/memory/helper.go, pkg/agent/evictionmanager/plugin/memory/numa_pressure.go, pkg/agent/evictionmanager/plugin/memory/system_pressure.go, pkg/agent/evictionmanager/plugin/resource/resources.go, pkg/agent/resourcemanager/fetcher/manager.go
enhancements
refactor healthz rules for eviction manager and reporter manager
=> feat(agent): refactor eviction/reporter healthz rule

pkg/controller/kcc/kcct.go, pkg/controller/kcc/kcct_test.go
=> refine and fix checkLabelSelectorOverlap

cmd/katalyst-agent/app/options/global/base.go, pkg/config/agent/global/base.go, pkg/util/machine/topology.go, pkg/util/machine/topology_test.go
Enhancements
Refine `GetSiblingNumaInfo` logic support sibling numa distance larger than the distance to itself
=> refine GetSiblingNumaInfo

cmd/katalyst-agent/app/options/qrm/cpu_plugin.go, pkg/agent/qrm-plugins/commonstate/types.go, pkg/agent/qrm-plugins/cpu/consts/consts.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpuadvisor/helper.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/validator/validator_cpu_advisor.go, pkg/agent/qrm-plugins/cpu/util/util.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/util/consts.go, pkg/config/agent/qrm/cpu_plugin.go, pkg/util/machine/util.go
feat(qrm): support shared_cores with numa_binding
=> feat(qrm): support shared_cores with numa_binding

cmd/katalyst-agent/app/options/sysadvisor/sysadvisor_base.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go, pkg/agent/sysadvisor/metacache/metacache.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go, pkg/agent/sysadvisor/plugin/metacache/metacache.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_load.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/memory.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memset_binder.go, pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go, pkg/agent/sysadvisor/types/helper.go, pkg/config/agent/sysadvisor/sysadvisor_base.go, pkg/util/general/common_suffix_translator.go, pkg/util/general/common_suffix_translator_test.go
Features
Support share cores with NUMA binding
=> support share cores with numa binding

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
fix(qrm): make ramp up cpus not overlapping with cpus in NUMAs containing NUMA_binding pods
=> fix(qrm): make ramp up cpus not overlapping with cpus in NUMAs containing NUMA_binding pods

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go
Enhancements
use aysnc limited workers to limit concurrency for move_pages action, to reduce  numa memory bandwidth occupancy and latencey
=> feat(qrm): move_pages use async limited workers

pkg/metaserver/spd/cache.go
Bug fixes
fix spd cache clear when checkpoint deleted
=> fix spd cache clear when checkpoint deleted

cmd/katalyst-agent/app/options/qrm/io_plugin.go, pkg/agent/qrm-plugins/io/handlers/iocost/const.go, pkg/agent/qrm-plugins/io/handlers/iocost/iocost_linux.go, pkg/agent/qrm-plugins/io/handlers/iocost/iocost_linux_test.go, pkg/agent/qrm-plugins/io/handlers/ioweight/ioweight_linux.go, pkg/agent/qrm-plugins/io/handlers/ioweight/ioweight_linux_test.go, pkg/config/agent/qrm/io_plugin.go
Bug fixes
[bugfix] Missing pod level setting for io.weight
Missing pod level setting for io.weight
None
=> ioweight: adding pod level setting

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
fix(qrm): populate not preferred hints by filterout available NUMA nodes
=> fix(qrm): populate not preferred hints by filterout available NUMA nodes

cmd/katalyst-agent/app/options/metaserver/metaserver.go, pkg/config/agent/metaserver/spd.go, pkg/controller/spd/indicator-plugin/manager.go, pkg/controller/spd/indicator-plugin/plugin.go, pkg/controller/spd/indicator-plugin/plugins/ihpa/plugin.go, pkg/controller/spd/indicator-plugin/plugins/resource-portrait/indicator_plugin.go, pkg/controller/spd/spd.go, pkg/controller/spd/spd_indicator.go, pkg/controller/spd/spd_test.go, pkg/metaserver/spd/fetcher.go, pkg/metaserver/spd/fetcher_test.go, pkg/util/spd.go
https://github.com/kubewharf/katalyst-core/pull/558/commits
https://github.com/kubewharf/katalyst-core/pull/561/commits
agent get SPD syncly & spd creation improvement
=> agent get SPD syncly & spd creation improvement

cmd/katalyst-agent/app/options/metaserver/metaserver.go, pkg/config/agent/metaserver/spd.go, pkg/metaserver/spd/fetcher.go
=> spd fetcher add config for enable service profile namespaces

cmd/katalyst-agent/app/options/qrm/qrm_base.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/cpu/nativepolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/network/staticpolicy/policy.go, pkg/agent/qrm-plugins/util/consts.go, pkg/agent/qrm-plugins/util/util.go, pkg/agent/qrm-plugins/util/util_test.go, pkg/config/agent/qrm/qrm_base.go, pkg/util/general/common.go, pkg/util/general/deepcopy.go, pkg/util/general/deepcopy_test.go, pkg/util/machine/bitmask.go, pkg/util/machine/topology.go, pkg/util/machine/util.go, pkg/util/machine/util_test.go
1. perf(qrm): improve performance of calculating hints 
3. feat(qrm): involve memory bandwidth when admitting in cpu plugin
=> 1. perf(qrm): improve performance of calculating hints 2. feat(qrm): involve memory bandwidth when admitting in cpu plugin

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
Enhancements
remove dropcache directly and use move_page to migrate cache
dropcache operation can cause jitter in some sensitive small containers.
=> feat(qrm): remove dropcache when migrate numa memory

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common_test.go
=> fix(sysadvisor): fix isolacted size calculated incorrectly

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_util.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go, pkg/metaserver/agent/metric/helper/reclaim.go
=> refine pressure_supression eviction and getUtilBasedHeadroom

pkg/agent/qrm-plugins/network/staticpolicy/policy.go, pkg/agent/qrm-plugins/network/staticpolicy/policy_test.go, pkg/metaserver/external/cgroupid/manager.go, pkg/util/external/network/manager.go, pkg/util/external/network/manager_linux.go, pkg/util/external/network/manager_unsupported.go
=> support clear residual net class

pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go, pkg/util/general/file.go, pkg/util/kubelet/podresources/client.go
Bug fixes
Fix race condition regarding orm and reporter start order.
In ORM mode, kubelet reporter plugin get topology info from ORM's out-of-band PodResources API, rather than kubelet's native PodResources API. If reporter starts before ORM, it can not get the socket of PodResources Server.
Error log:
```
E0807 17:58:09.245252       1 manager.go:403] GetReportContentResponse from kubelet-reporter-plugin Endpoint failed with error: get numa topology status from adapter failed: list pod from pod resource server failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix: missing address"
```
So I extracted the PodResources client to a common util and added a retry mechanism.
=> fix(reporter): fix race condition regarding orm and reporter start order

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go, pkg/util/machine/cpu.go, pkg/util/machine/cpu_test.go
=> feat: support to update reservedForReclaim dynamicly

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
Bug fixes
Fix snb pool size calc
=> feat(advisor): fix advisor snb pool size calc

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go
Bug fixes
Fix reclaimed cores topology hints
=> feat(qrm): fix reclaimed cores topology hints

pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin_test.go, pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go, pkg/agent/sysadvisor/plugin/overcommitmentaware/realtime/realtime_test.go, pkg/agent/sysadvisor/plugin/overcommitmentaware/reporter/reporter_test.go, pkg/metaserver/agent/agent_test.go, pkg/metaserver/agent/kubeletconfig/fake_kubeletconfig.go, pkg/metaserver/agent/kubeletconfig/kubeletconfig.go, pkg/util/kubelet/config/kubeletconfig.go, pkg/util/kubelet/config/kubeletconfig_test.go, pkg/util/native/kubelet.go, pkg/util/native/kubelet_test.go
Bug fixes
Extract the definition of `KubeletConfiguration` from the kubelet API repository to the katalyst repository to adapt to incompatible changes of kubelet's `/configz` endpoint which were introduced by https://github.com/kubernetes/kubernetes/pull/117800.
=> fix(*): adapt to kubelet configz endpoint changes to support K8s 1.28

cmd/katalyst-agent/app/options/reporter/kubelet_plugin.go, pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go, pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go, pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go, pkg/config/agent/reporter/kubelet_plugin.go
Enhancements
The topology adapter can use not only the native resource plugin state file but also other files, such as the QRM resource plugin state file, when the native resource plugin state file is unavailable.
=> topology adapter support configure custom kubelet resource plugin state file

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_checkpoint.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/util.go, pkg/agent/qrm-plugins/cpu/nativepolicy/policy.go, pkg/agent/qrm-plugins/cpu/nativepolicy/policy_test.go, pkg/agent/qrm-plugins/cpu/nativepolicy/util/util.go
if we want to add a new strategy, this refactoring will be helpful.
=> refactor(qrm): refactor the state module for enhanced extensibility

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/util.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_async_handler.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/state/state.go
Enhancements
In certain situations, a pod with the system_cores QoS level should be bound to specific CPU pools, such as the reserve pool, to prevent impact on critical pools.
=> system_cores support set specific pool

Makefile, cmd/katalyst-agent/app/options/qrm/memory_plugin.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/vpa_test.go, pkg/agent/qrm-plugins/cpu/util/util.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/vpa_test.go, pkg/agent/qrm-plugins/util/util.go, pkg/config/agent/qrm/memory_plugin.go
Bug fixes
Fix cpu admit failed caused by float ceil
=> fix(qrm): fix cpu admit failed caused by float ceil

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_offloading.go, pkg/util/cgroup/manager/cgroup.go, pkg/util/cgroup/manager/cgroup_test.go
refactor: make kernel allocate zram memory at allowed NUMAs of workload process
Enhancements
=> refactor: make kernel allocate zram memory at allowed NUMAs of workload process

cmd/katalyst-agent/app/options/qrm/memory_plugin.go, pkg/agent/qrm-plugins/memory/consts/consts.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/handlers/fragmem/const.go, pkg/agent/qrm-plugins/memory/handlers/fragmem/fragmem_linux.go, pkg/agent/qrm-plugins/memory/handlers/fragmem/fragmem_linux_test.go, pkg/agent/qrm-plugins/memory/handlers/fragmem/fragmem_unsupported.go, pkg/agent/qrm-plugins/memory/handlers/fragmem/utils_linux.go, pkg/config/agent/qrm/memory_plugin.go, pkg/consts/metric.go, pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go, pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go, pkg/metaserver/agent/metric/provisioner/malachite/types/system.go, pkg/util/process/system.go, pkg/util/process/system_test.go
Features: adding support for memory fragmentation management
In production area, memory fragmentation related issues can cause numerous problems.
Many issues.
None.
=> feat(fragmem): unified solution for memory compaction

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux_test.go
Enhancements：ensure consistency in the values of tcp_mem to reduce tcp memory pressure.
None
None
None
=> feat(sockmem): keep the values in tcp_mem consistent

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/util/cgroup/common/cgroup_linux.go, pkg/util/cgroup/common/cgroup_linux_test.go, pkg/util/cgroup/manager/v1/fs_linux.go, pkg/util/cgroup/manager/v2/fs_linux.go
Bug fix
Fix getting numa memory stats under cgroup v1.
=> fix(qrm): fix printing of numa mem migrate container stats

cmd/katalyst-agent/app/options/metaserver/metric.go, pkg/agent/sysadvisor/plugin/poweraware/advisor/advisor.go, pkg/agent/sysadvisor/plugin/poweraware/power_aware.go, pkg/agent/sysadvisor/plugin/poweraware/reader/metric_store_power_reader.go, pkg/agent/sysadvisor/plugin/poweraware/reader/metric_store_power_reader_test.go, pkg/config/agent/metaserver/agent.go, pkg/consts/metric.go, pkg/metaserver/agent/metric/metric_provisoner.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client_power.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client_power_test.go, pkg/metaserver/agent/metric/provisioner/malachite/realtime_provisioner.go, pkg/metaserver/agent/metric/provisioner/malachite/realtime_provisioner_test.go, pkg/metaserver/agent/metric/provisioner/malachite/types/power.go
Feature: power aware advisor uses realtime power data originally from malachite. It has 3 major parts:
* malachite client method to get power stats from metric service path realtime/power;
* malachite_realtime provisioner which samples (in higher frequency) using malachite client and saves power metric in metric store;
* a power reader adapted to get power data out of metric store; 
part of power node agent, it is needed for power aware plugin to get the current power usage and hence identify whether further measures required to limit the power consumption comparing with the desired power target.
NA
=> feat (sysadvisor): get power data served by metric store sourced from malachite realtime metric server

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter.go, pkg/util/cgroup/common/types.go, pkg/util/cgroup/manager/cgroup.go, pkg/util/cgroup/manager/cgroup_test.go, pkg/util/cgroup/manager/v1/fs_linux.go, pkg/util/cgroup/manager/v2/fs_linux.go
=> fix(*): empty cpuset.mems will lead to failure of tmo

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_test.go, pkg/agent/qrm-plugins/cpu/nativepolicy/policy.go, pkg/agent/qrm-plugins/cpu/nativepolicy/policy_test.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/state/state.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/state/state_test.go
Enhancements
To enhance scalability, we are refactoring the CPU/memory plugin state in QRM to support a read-write interface for situations where asynchronous state updates are necessary.
=> Refactor qrm state

pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go
=> fix(*): Remove the constraints on move pages

pkg/util/cgroup/manager/cgroup.go, pkg/util/cgroup/manager/cgroup_linux.go, pkg/util/cgroup/manager/cgroup_unsupported.go
=> chore(cgroup): add condition compile for IsCgroupPath

pkg/agent/sysadvisor/plugin/poweraware/advisor/action/strategy/strategy.go, pkg/agent/sysadvisor/plugin/poweraware/advisor/action/strategy/strategy_test.go, pkg/agent/sysadvisor/plugin/poweraware/capper/server/service.go, pkg/agent/sysadvisor/plugin/poweraware/evictor/server/evictor_service.go, pkg/agent/sysadvisor/plugin/poweraware/evictor/server/evictor_service_test.go, pkg/agent/sysadvisor/plugin/poweraware/power_aware.go
Bug fixes
this PR has 3 fixes:
1.  explicit internal-op over autonomy in last 2 minutes (behavior change);
2. power cap sock file folders creation in case it is not there;
3. split power cap server and plugin to avoid recursive reference chain via plugin wrapper
=> fix (sysadvisor): pap - fixes of defects identified in integration validation

pkg/agent/sysadvisor/plugin/poweraware/advisor/action/strategy/dvfs_tracker.go, pkg/agent/sysadvisor/plugin/poweraware/advisor/action/strategy/dvfs_tracker_test.go, pkg/agent/sysadvisor/plugin/poweraware/advisor/action/strategy/evict_first.go, pkg/agent/sysadvisor/plugin/poweraware/advisor/action/strategy/evict_first_test.go, pkg/agent/sysadvisor/plugin/poweraware/advisor/action/strategy/strategy.go, pkg/agent/sysadvisor/plugin/poweraware/advisor/advisor.go, pkg/agent/sysadvisor/plugin/poweraware/advisor/reconciler.go, pkg/agent/sysadvisor/plugin/poweraware/advisor/reconciler_test.go, pkg/agent/sysadvisor/plugin/poweraware/capper/server/service.go, pkg/agent/sysadvisor/plugin/poweraware/evictor/percentage_evictor.go, pkg/agent/sysadvisor/plugin/poweraware/evictor/percentage_evictor_test.go, pkg/agent/sysadvisor/plugin/poweraware/power_aware.go, pkg/agent/sysadvisor/plugin/poweraware/power_aware_test.go
Features + Enhancements
this PR mainly introduces the evict-first strategy which, for power alert P0, would evict low qos pods first if any, and only after they are exhausted will it tries to resort to DVFS(power capping) within the constraint limit. Besides, it keeps yielding suitable action plan as long as the power spec exists.
Its another enhancement is using ceiling math to calculate the number of pods to evict; this is necessary as we need to ensure the low qos pod could be exhausted, otherwise the constraint DVFS plan cannot be yield. 
This ecivt-first strategy is designed to work better with the multi-round governing DC/cluster power alert controller.
=> feat(sysadvisor): pap - evict first strategy for power control plan

pkg/metaserver/agent/metric/provisioner/malachite/realtime_provisioner.go
Bug fixes
uses malachite realtime provisioner health check name via RegisterHeartbeatCheck
current code improperly sticks to the regular malachite health check name, which brings about emits times more metrics that would have gone to malachite realtime sampler to the regular malachite.
=> fix(sysadvisor): trivial - malachite realtime provisioner health check name

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_none.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/regulator/regulator.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go, pkg/agent/sysadvisor/types/cpu.go, pkg/util/machine/cpu.go
1. no need to round requirement if cpuset overlapped
2. get effective control knobs by regionInfo for dedicated_cores
=> fix(sysadvisor): fix provision logic of dedicated_cores region

pkg/agent/evictionmanager/manager.go
=> fix eviction manager getEvictPodFromCandidates sort order

pkg/metaserver/agent/metric/provisioner/malachite/client/client.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client_cgroup.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client_cgroup_test.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client_pod.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client_pod_test.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client_power.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client_power_test.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client_system.go, pkg/metaserver/agent/metric/provisioner/malachite/client/client_system_test.go, pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go, pkg/metaserver/agent/metric/provisioner/malachite/realtime_provisioner.go
=> feat(metrics): emit metrics for out-of-date/missing malachite data

pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_util.go, pkg/util/cnr_topology.go
=> fix(sysadvisor): get util based headroom per-numa

pkg/agent/sysadvisor/plugin/poweraware/advisor/action/strategy/evict_first.go, pkg/agent/sysadvisor/plugin/poweraware/advisor/action/strategy/evict_first_test.go, pkg/agent/sysadvisor/plugin/poweraware/reader/metric_store_power_reader.go, pkg/agent/sysadvisor/plugin/poweraware/reader/metric_store_power_reader_test.go
Bug fixes/Enhancements
this PR has 2 parts:
* minor bug fix that treating power usage of 0 as error - it is actually caused by malachite realtime power service feeding null response - so that the reader error metric would catch such case;
* slight change of implications of alert level p1 and internal-op supplementation - in short, p1 not to evict anymore, and power-cap internal-op only applicable at level s0&p0 (dvfs-related levels) - this semantic change is part of iteration of power aware development in 2025 Q1
| level | Default allowed action |  
| --- | --- | --- |
| S0 | Power cap | unconstrained dvfs cap |
| P0 | Evict first;Up to 10% DVFS power reduction if low-qos pod exhausted | w/ internal-op it may result in variant:1 - evict only;2- constrained DVFS reduction only |
| P1 | No …
=> fix(sysadvisor): pap - level p1 action plan not to evict

pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
Bug fixes
When performing inference in the Borwein model, we found that some metrics are missing when the node is in CGroupV2 mode. This, in turn, causes the inference feature to be 0. Therefore, we need to supplement these metrics and ensure that the calculation criteria are consistent with those of the Malachite Reporter.
some metrics are missing when the node is in CGroupV2 mode
(cpu.share.container, cpu.period.container, cpu.quota.container)
=> fix(sysadvisor): supplement the missing metrics in CGroupV2

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux.go
Enhancements: optimize the fail handling of sockmem plugin
Too many unnecessary failed logs in  the current sockmem plugin
None
This PR has been vailified in several producation clusters.
=> sockmem: optimize the fail handling

pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/latencyregression/latency_regression.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/latencyregression/latency_regression_test.go
Features
To make the prediction results more accurate, a new field `ignore` is added in the Borwein Latency Regression, and small-scale services are excluded
=> feat(sysadvisor): add ignore check in borwein model

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
Bug fix
Currently some annotations (including `numa_hint`) is missing in sidecar container allocation info in qrm cpu plugin state. This will result in sysadvisor update failure when SNB sidecar containers are present.
=> fix(qrm-plugins): populate sidecar container annotations

pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
Bug fixes
Avoid error when fetching malachite system info failed
=> fix(sysadvisor): avoid error when fetching malachite system info failed

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler_test.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
Features
Introduce a new metric `pod_total_request_larger_than_cpu_set` to track cases where the total CPU request of a pod exceeds the size of its allocated CPU set. This helps in identifying resource allocation issues and ensuring proper CPU utilization.
=> feat(cpu/dynamicpolicy): add metrics for CPU request exceeding CPU set size

Makefile, go.mod, pkg/util/machine/network_linux.go, pkg/util/machine/network_linux_test.go
Bug fixes
Add a check using the mountinfo package to verify if sysfs is already mounted before attempting to mount it. This prevents redundant mount operations and potential errors when switching network namespaces.
=> fix(network): check if sysfs is mounted before mounting

pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_offloading.go
Bug fixes
remove memory advisor the check for offloading target size less than or equal to zero to fix swap not off when target pod tmo is disabled.
=> fix(tmo): remove target size zero check to fix swap not off

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
Bug fixes
Update the log message to accurately reflect CPU hints instead of memory hints. Additionally, modify the topology hint logic to set the preferred flag based on the current available resources, ensuring correct resource allocation.
=> fix(cpu): correct log message and adjust topology hint preference

pkg/util/native/kubelet.go, pkg/util/native/kubelet_test.go
Bug fixes
for ipv6 only enviroment, katalyst does not work
ipv6 compatible when requesting Kubelet
=> chore(*): fix kubelet endpoint do not support ipv6

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go, pkg/agent/qrm-plugins/network/staticpolicy/policy.go, pkg/agent/qrm-plugins/util/consts.go, pkg/agent/qrm-plugins/util/util.go
Observation metric enhancement 
When resource allocation fails, it indicates whether it is the first allocation or reallocation.
Add `reallocated` tag to `katalyst.alloc_failed` metric
=> feat(*): add a reallocate tag to the MetricNameAllocateFailed metric

pkg/agent/sysadvisor/plugin/poweraware/capper/instruction.go, pkg/agent/sysadvisor/plugin/poweraware/capper/server/service.go, pkg/agent/sysadvisor/plugin/poweraware/capper/server/service_test.go, pkg/agent/sysadvisor/plugin/poweraware/metric/emit_metric.go, pkg/agent/sysadvisor/plugin/poweraware/metric/metric_tag.go
Enhancements - power cap advisor supports GetAdvice unary GRPC protocol, with long polling ability
This PR implements GetAdvice method of new advisor-qrm communication protocol. To avoid communication overhead, it  leverages long-polling so as to reduce the client requests resulting empty responses.
=> enhance(advisor): power cap service supports GetAdvice

cmd/katalyst-agent/app/options/sysadvisor/qosaware/model/borwein/borwein.go, pkg/agent/qrm-plugins/network/staticpolicy/policy.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/latencyregression/latency_regression.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/latencyregression/latency_regression_test.go, pkg/agent/sysadvisor/plugin/inference/models/borwein/types/types.go, pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/model.go, pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go, pkg/config/agent/sysadvisor/qosaware/model/borwein/borwein.go, pkg/util/strategygroup/strategy_group.go
Features
Previously, we have launched the Borwein V2 strategy: requesting inference results from the Borwein Inference Server and writing the inference results into KCMAS. This time, we support adjusting the Offset value of the Indicator in Rama based on the inference results of Borwein.
In order to better observe and compare the performance of the Borwein strategy through the AB Test method, we have integrated the StrategyGroup capability. Based on StrategyGroup, we can dynamically group and control whether the Borwein strategy is enabled on nodes.
In order to flexibly compare the business performance at the node level with the historical business performance of the cluster, we issue the historical NET performance of the cluster based on StrategyGroup, and adjust Borwein according to the …
=> feat(sysadvisor): support indicator offset update by borwein

pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/numa_history.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_metric.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_numa.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_numa_test.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_threshold.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_threshold_test.go, pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/node.go, pkg/agent/sysadvisor/types/cpu.go, pkg/config/agent/dynamic/adminqos/eviction/eviction_base.go, pkg/config/agent/dynamic/adminqos/eviction/numa_cpu_pressure_eviction.go, pkg/consts/strategy_names.go, pkg/metaserver/agent/metric/helper/system.go, pkg/metaserver/agent/metric/helper/system_test.go
Features
A new Eviction Plugin has been implemented. It retrieves the CPU usage of shared_cores at the NUMA level. Based on this, it compares the CPU usage with the thresholds set for different machine types and isVM, and then realizes the eviction of Pods. If all NUMA nodes are overloaded, a taint will be added to the entire machine.
=> feat(qrm): support numa cpu pressure eviction

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
Enhancements
Modify the pool size metric tracking to report sizes per NUMA node instead of the entire pool. This provides more detailed insights into resource allocation and utilization across different NUMA nodes.
=> refactor(cpu/dynamicpolicy): track pool size per NUMA node for better granularity

cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_isolation.go, pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go, pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
Enhancements
Introduce a new configuration flag `IsolationIncludeSidecarRequirement` to optionally include sidecar container requirements when calculating CPU isolation. This allows for more flexible resource allocation in environments where sidecar containers have significant resource needs.
=> feat(cpu): add sidecar requirement inclusion in CPU isolation

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go, pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go, pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_linux_test.go, pkg/util/cgroup/common/cgroup_linux.go, pkg/util/cgroup/common/cgroup_linux_test.go, pkg/util/cgroup/common/cgroup_unsupported.go, pkg/util/cgroup/common/types.go
Bug fixes
Introduce a custom CgroupResources type to decouple from the libcontainer configs.Resources dependency. This improves maintainability and reduces external dependencies. The toConfigsResources helper function is added to convert ConfigResources to libcontainer's configs.Resources when necessary.
=> refactor(cgroup): replace libcontainer configs.Resources with custom CgroupResources

pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_offloading.go
Bug fixes
The numa exclusive check was redundant since we already check for reclaimability. This simplifies the condition while maintaining the same behavior.
=> fix: remove redundant numa exclusive check for memory offloading

pkg/agent/qrm-plugins/advisorsvc/advisor_svc.pb.go, pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_async_handler.go, pkg/util/cgroup/common/path.go, pkg/util/cgroup/common/path_test.go
Enhancements
check cgroup file's existence before apply data for container in applyExternalCgroupParams to avoid unnecessary health check failed
=> check cgroup file's existence before apply data for container in applyExternalCgroupParams

pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go
Bug fixes
The change replaces all occurrences of "newCNR" with "cnr" in variable names, comments, and log messages to maintain consistent terminology throughout the codebase. This improves code readability and reduces confusion between different naming conventions.
=> fix(cnrreporter): rename newCNR references to cnr for consistency

pkg/metaserver/kcc/manager.go
Bug fixes
Use MetricTypeNameRaw instead of MetricTypeNameCount for checkpoint load failure metric to properly reflect the metric type
=> fix: correct metric type for checkpoint load failure

pkg/agent/evictionmanager/manager.go, pkg/agent/evictionmanager/podkiller/podkiller.go, pkg/agent/evictionmanager/podkiller/podkiller_test.go
Enhancements
Add pod UID to eviction key to ensure uniqueness and prevent conflicts with same-named pods. Include pod fetcher from meta server to verify pod existence during eviction process.
=> feat(evictionmanager): add pod uid to eviction key and fetcher support

cmd/katalyst-agent/app/options/qrm/cpu_plugin.go, pkg/agent/qrm-plugins/cpu/dynamicpolicy/calculator/cpu_assignment.go, pkg/agent/qrm-plugins/cpu/util/util.go, pkg/agent/qrm-plugins/cpu/util/util_test.go, pkg/config/agent/qrm/cpu_plugin.go
By default, the  cpu reserved starts from the cpu with lower id, in some cases, we want to avoiding reserve 0-core, so this PR introduce a switch to enable reserve cpu reversely.
=> feat: support allocate reserve cpu reversely

pkg/consts/common.go, pkg/consts/metric.go, pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go, pkg/metaserver/agent/metric/provisioner/malachite/provisioner_calculate.go, pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go, pkg/metaserver/agent/metric/provisioner/malachite/types/common.go, pkg/metaserver/agent/metric/provisioner/malachite/types/system.go, pkg/util/metric/store_util.go
- fixed the issue to calculate the numa memory bandwidth using malachite-core raw data.
- calculate the bps per l3 cache
- aggregate numa bps using l3 cache bps
=> fix(sysadvisor): fix kcmas resctrl reported memory bandwidth calculation issue

pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/latencyregression/latency_regression.go, pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/latencyregression/latency_regression_test.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go, pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go, pkg/config/agent/sysadvisor/qosaware/model/borwein/borwein.go
Features
1. update borwein parameters
2. when current NET met no strategy slot, use latest one, not indicator max, to 
3. during special time, do not expand indicator min (no need to do that)
=> feat(advisor): update borwein offset calculation

pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
fixes
The interrupt pool will be initialized by default. If only qrm is upgraded, the order will be stuck.
the interrupt pool is initialized only when irqtuner is enabled
=> fix(*): the interrupt pool is initialized only when irqtuner is enabled

pkg/util/machine/network.go, pkg/util/machine/network_linux.go
Bug fixes
Move the UnknownNumaNode constant from network_linux.go to network.go to make it available across all platforms and avoid duplication
=> refactor(network): move UnknownNumaNode constant to common file
